In [12]:
import requests

import pandas as pd

from bs4 import BeautifulSoup

from datetime import datetime

import pandas as pd

from textblob import TextBlob




from nltk.sentiment import SentimentIntensityAnalyzer

import nltk

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/annabelitong/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/annabelitong/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/annabelitong/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/annabelitong/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [2]:
df10= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2010_season_aggregate.csv')
df11= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2011_season_aggregate.csv')
df12= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2012_season_aggregate.csv')
df13= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2013_season_aggregate.csv')
df14= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2014_season_aggregate.csv')
df15= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2015_season_aggregate.csv')
df16= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2016_season_aggregate.csv')
df17= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2017_season_aggregate.csv')
df23= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2023_season_aggregate.csv')
df18= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2018_season_aggregate.csv')
df19= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2019_season_aggregate.csv')
df20= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2020_season_aggregate.csv')
df21= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2021_season_aggregate.csv')
df22= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2022_season_aggregate.csv')

In [3]:
def get_bbc_textblob_sentiment(url):
    r = requests.get(url)
    soup = BeautifulSoup(r.content, "html.parser") 
    content = soup.find("div", attrs={"class": "gel-layout__item gel-2/3@l"})
    
    if content is None:
        return None

    main_body = content.find_all('p')
    text = ""
    for i in main_body:
        text += i.text
    clean_text = text.replace('\n', ' ').replace('\xa0', '')
    blob = TextBlob(clean_text)
    sentiment = blob.sentiment
    polarity = sentiment.polarity  # Assess sentiment polarity (-1 to 1)
    return polarity

In [10]:
df10['textblob_Sentiment'] = None

# Iterate over each row in the DataFrame
for index, row in df10.iterrows():
    url = row['url']
    sentiment = get_bbc_textblob_sentiment(url)
    df10.at[index, 'textblob_Sentiment'] = sentiment

# Print the DataFrame with the added 'Sentiment' column
print(df10)

      Unnamed: 0                                              title     date  \
0              0  Kevin Durant: Phoenix Suns forward out for thr...  2022-23
1              1  NBA: Kevin Durant scores 23 points on Phoenix ...  2022-23
2              2  NBA: Kevin Durant traded to Phoenix Suns as Ru...  2022-23
3              3  NBA All-Star Game: Giannis Antetokounmpo MVP a...  2020-21
4              4  NBA: Brooklyn Nets find 'solace' in wins after...  2022-23
...          ...                                                ...      ...
8639       16935          NFL draft 2021: Meet the top 10 prospects  2020-21
8640       16937                                        MBEs: A - C  2001-02
8641       16941                     Colin's Trunk of Funk playlist  2009-10
8642       16942  Super Bowl LII: A frosty welcome for Eagles in...  2017-18
8643       16945  General election 2019: Who is standing in Scot...  2019-20

                                                    url        player  \
0       https://www.bbc.co.uk/sport/basketball/64912266  Kevin Durant
1       https://www.bbc.co.uk/sport/basketball/64820742  Kevin Durant
2       https://www.bbc.co.uk/sport/basketball/64593463  Kevin Durant
3       https://www.bbc.co.uk/sport/basketball/56318297  Kevin Durant
4       https://www.bbc.co.uk/sport/basketball/63532635  Kevin Durant
...                                                 ...           ...
8639  https://www.bbc.co.uk/sport/american-football/...     Raja Bell
8640  http://news.bbc.co.uk/1/hi/in_depth/uk/2002/ne...     Raja Bell
8641  http://news.bbc.co.uk/local/shropshire/hi/tv_a...     Raja Bell
8642  https://www.bbc.co.uk/sport/american-football/...     Raja Bell
8643  https://www.bbc.co.uk/news/election-2019-50437627     Raja Bell

     textblob_Sentiment
0              0.109138
1              0.163115
2              0.088472
3              0.174322
4              0.089537
...                 ...
8639           0.165787
8640               None
8641               None
8642           0.144484
8643               None

[8644 rows x 6 columns]

In [19]:
df10.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2010_assessed_2.csv', index=False)

In [35]:
df_10 = df10.copy()
df_10_filtered = df_10[(df_10['date'] == '2010-11')]
df_10_filtered = df_10_filtered.dropna(subset=['textblob_Sentiment'])

In [36]:
df_10_filtered.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2010_seperate_assessed_2.csv', index=False)

In [54]:
df10

,Unnamed: 0,title,date,url,player,textblob_Sentiment
0,0,Kevin Durant: Phoenix Suns forward out for thr...,2022-23,https://www.bbc.co.uk/sport/basketball/64912266,Kevin Durant,0.109138
1,1,NBA: Kevin Durant scores 23 points on Phoenix ...,2022-23,https://www.bbc.co.uk/sport/basketball/64820742,Kevin Durant,0.163115
2,2,NBA: Kevin Durant traded to Phoenix Suns as Ru...,2022-23,https://www.bbc.co.uk/sport/basketball/64593463,Kevin Durant,0.088472
3,3,NBA All-Star Game: Giannis Antetokounmpo MVP a...,2020-21,https://www.bbc.co.uk/sport/basketball/56318297,Kevin Durant,0.174322
4,4,NBA: Brooklyn Nets find 'solace' in wins after...,2022-23,https://www.bbc.co.uk/sport/basketball/63532635,Kevin Durant,0.089537
...,...,...,...,...,...,...
8639,16935,NFL draft 2021: Meet the top 10 prospects,2020-21,https://www.bbc.co.uk/sport/american-football/...,Raja Bell,0.165787
8640,16937,MBEs: A - C,2001-02,http://news.bbc.co.uk/1/hi/in_depth/uk/2002/ne...,Raja Bell,None
8641,16941,Colin's Trunk of Funk playlist,2009-10,http://news.bbc.co.uk/local/shropshire/hi/tv_a...,Raja Bell,None
8642,16942,Super Bowl LII: A frosty welcome for Eagles in...,2017-18,https://www.bbc.co.uk/sport/american-football/...,Raja Bell,0.144484
8643,16945,General election 2019: Who is standing in Scot...,2019-20,https://www.bbc.co.uk/news/election-2019-50437627,Raja Bell,None

In [ ]:


df12['textblob_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df12.iterrows():
    url = row['url']
    sentiment = get_bbc_textblob_sentiment(url)
    df12.at[index, 'textblob_Sentiment'] = sentiment

In [55]:
df12.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2012_assessed_2.csv', index=False)

In [48]:

df_12 = df12.copy()
df_12_filtered = df_12[(df_12['date'] == '2012-13')]
df_12_filtered = df_12_filtered.dropna(subset=['textblob_Sentiment'])

In [49]:
df_12_filtered

,Unnamed: 0,title,date,url,player,textblob_Sentiment
662,1136,Plymouth Raiders: Jeremy Bell leaves Devon club,2012-13,https://www.bbc.co.uk/sport/basketball/20945466,Kevin Love,0.165544
740,1277,Queen of the South 4-1 Stranraer,2012-13,https://www.bbc.co.uk/sport/football/20828892,Kevin Love,0.033333
780,1375,Hull KR 6-84 Wigan,2012-13,https://www.bbc.co.uk/sport/rugby-league/21957133,Blake Griffin,0.081022
794,1409,Super League 2013: Club-by-club season preview,2012-13,https://www.bbc.co.uk/sport/rugby-league/21164401,Blake Griffin,0.175496
889,1580,Sloane Stephens enters the big time with win o...,2012-13,https://www.bbc.co.uk/sport/tennis/21166123,Dirk Nowitzki,0.139262
...,...,...,...,...,...,...
4976,9879,Tuesday's gossip column,2012-13,https://www.bbc.co.uk/sport/21664714,José Calderón,0.111888
5030,9982,Results from 2012,2012-13,https://www.bbc.co.uk/sport/boxing/20935248,Ricky Rubio,0.070754
5126,10185,BBL Cup Final: Leicester Riders beat Newcastle...,2012-13,https://www.bbc.co.uk/sport/basketball/20973834,Anderson Varejão,0.147115
5194,10331,James Alexander Gordon: The voice behind the c...,2012-13,https://www.bbc.co.uk/sport/football/20449507,Eric Gordon,0.173226
5317,10652,BBL Cup Final: Leicester Riders beat Newcastle...,2012-13,https://www.bbc.co.uk/sport/basketball/20973834,Andrew Bogut,0.147115

In [50]:
df_12_filtered.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2012_seperate_assessed_2.csv', index=False)

In [ ]:



df13['textblob_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df13.iterrows():
    url = row['url']
    sentiment = get_bbc_textblob_sentiment(url)
    df13.at[index, 'textblob_Sentiment'] = sentiment

In [56]:
df13.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2013_assessed_2.csv', index=False)

In [46]:

df_13 = df13.copy()
df_13_filtered = df_13[(df_13['date'] == '2013-14')]
df_13_filtered = df_13_filtered.dropna(subset=['textblob_Sentiment'])

df_13_filtered.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2013_seperate_assessed_2.csv', index=False)

In [47]:
df_13_filtered

,Unnamed: 0,title,date,url,player,textblob_Sentiment
208,352,Kobe Bryant drops Â£3.71m to stay at LA Lakers...,2013-14,https://www.bbc.co.uk/sport/basketball/25095610,Kobe Bryant,0.00767
468,790,LeBron James in talks on David Beckham Miami M...,2013-14,https://www.bbc.co.uk/sport/football/24995887,LeBron James,0.222059
630,1072,LV=Cup: Scarlets 13-7 Gloucester,2013-14,https://www.bbc.co.uk/sport/rugby-union/25885845,James Harden,0.06
736,1250,Glasgow 2014: The Jamaican university that cha...,2013-14,https://www.bbc.co.uk/sport/commonwealth-games...,Carmelo Anthony,0.158894
1026,1741,Coach Stephen Keshi proud of Nigeria's CHAN ca...,2013-14,https://www.bbc.co.uk/sport/football/26007595,Stephen Curry,0.315657
...,...,...,...,...,...,...
5438,10920,Champions League draw: Man Utd v Bayern Munich...,2013-14,https://www.bbc.co.uk/sport/football/26682665,José Calderón,0.099901
5454,10945,Atletico Madrid: Diego Simeone's side are ster...,2013-14,https://www.bbc.co.uk/sport/football/26966304,José Calderón,0.100609
5460,10955,World Cup 2014: Belgium legends rule out glory...,2013-14,https://www.bbc.co.uk/sport/football/25210495,José Calderón,0.212614
5477,10995,"Gossip column: Kroos, Rodriguez, Casillas, Azm...",2013-14,https://www.bbc.co.uk/sport/26965549,José Calderón,0.11957
5486,11011,Champions League draw: Bayern Munich & PSG fac...,2013-14,https://www.bbc.co.uk/sport/football/26664718,José Calderón,0.150213

In [ ]:
  

df14['textblob_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df14.iterrows():
    url = row['url']
    sentiment = get_bbc_textblob_sentiment(url)
    df14.at[index, 'textblob_Sentiment'] = sentiment

In [57]:
df14.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2014_assessed_2.csv', index=False)

In [51]:

df_14 = df14.copy()
df_14_filtered = df_14[(df_14['date'] == '2014-15')].copy()
df_14_filtered = df_14_filtered.dropna(subset=['textblob_Sentiment'])

df_14_filtered.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2014_seperate_assessed_2.csv', index=False)

In [52]:
df_14_filtered

,Unnamed: 0,title,date,url,player,textblob_Sentiment
379,655,LeBron James' Cleveland Cavaliers NBA return e...,2014-15,https://www.bbc.co.uk/sport/basketball/29846598,LeBron James,0.155195
422,755,Kevin Pietersen: Eoin Morgan wants me in Engla...,2014-15,https://www.bbc.co.uk/sport/cricket/30794807,Kevin Love,0.0809
696,1259,Irish Premiership: Institute 1-1 Warrenpoint Town,2014-15,https://www.bbc.co.uk/sport/football/30606362,Stephen Curry,0.169231
719,1301,Irish Premiership: Ballinamallard Utd 3-1 Warr...,2014-15,https://www.bbc.co.uk/sport/football/30255666,Stephen Curry,0.081021
724,1308,Irish Premiership: Portadown 2-1 Institute,2014-15,https://www.bbc.co.uk/sport/football/30673066,Stephen Curry,0.122018
...,...,...,...,...,...,...
5845,11460,Super Bowl XLIX: 'NFL flourishes amid mayhem a...,2014-15,https://www.bbc.co.uk/sport/american-football/...,Jordan Crawford,0.084669
5942,11657,"Gossip column: Defoe, Silva, Rodriguez, Redkna...",2014-15,https://www.bbc.co.uk/sport/30807708,Ramon Sessions,0.142766
6052,11994,BBL Trophy final: Newcastle Eagles 96-90 Leice...,2014-15,http://www.bbc.co.uk/sport/basketball/32011667,Ryan Anderson,0.083257
6065,12015,Raith Rovers 2-1 Dumbarton,2014-15,https://www.bbc.co.uk/sport/football/30758640,Ryan Anderson,0.165785
6216,12318,Six Nations 2015: England bring in Geoff Parli...,2014-15,https://www.bbc.co.uk/sport/rugby-union/31932746,Brook Lopez,0.176984

In [58]:

df_11 = df11[(df11['date'] == '2011-12')].copy()
df_11['Senttextblob_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df_11.iterrows():
    url = row['url']
    sentiment = get_bbc_textblob_sentiment(url)
    df_11.at[index, 'textblob_Sentiment'] = sentiment

In [61]:
df_11 = df_11.drop('Senttextblob_Sentiment', axis=1)

In [63]:

df_11_filtered = df_11.dropna(subset=['textblob_Sentiment'])

df_11_filtered.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2011_seperate_assessed_2.csv', index=False)

In [65]:
df_11_filtered

,Unnamed: 0,title,date,url,player,textblob_Sentiment
71,118,London 2012: LeBron James and Kobe Bryant in U...,2011-12,https://www.bbc.co.uk/sport/basketball/16586122,Kevin Durant,0.238721
296,513,London 2012: LeBron James and Kobe Bryant in U...,2011-12,https://www.bbc.co.uk/sport/basketball/16586122,LeBron James,0.238721
323,569,NBA stars set for USA-Great Britain clash in M...,2011-12,https://www.bbc.co.uk/sport/basketball/17158534,LeBron James,0.279167
378,648,London 2012: LeBron James and Kobe Bryant in U...,2011-12,https://www.bbc.co.uk/sport/basketball/16586122,Kobe Bryant,0.238721
464,781,NBA stars set for USA-Great Britain clash in M...,2011-12,https://www.bbc.co.uk/sport/basketball/17158534,Kobe Bryant,0.279167
...,...,...,...,...,...,...
7554,14844,"Pakistan v England, third one-day internationa...",2011-12,https://www.bbc.co.uk/sport/cricket/17080332,Gilbert Arenas,0.126657
7563,14867,World Snooker Championship 2012: Who will rule...,2011-12,https://www.bbc.co.uk/sport/snooker/17720729,Gilbert Arenas,0.155689
7989,15671,RaboDirect Pro12: Cardiff Blues 19-23 Leinster,2011-12,https://www.bbc.co.uk/sport/rugby-union/16395420,Devin Harris,0.043638
8037,15765,London 2012: LeBron James and Kobe Bryant in U...,2011-12,https://www.bbc.co.uk/sport/basketball/16586122,Deron Williams,0.238721
8066,15830,London 2012: Olympic sport this week,2011-12,https://www.bbc.co.uk/sport/olympics/16678808,Deron Williams,0.216714

In [69]:
df_15 = df15[df15['date'] == '2015-16'].copy()
df_15['textblob_Sentiment'] = None  # Corrected column name

# Iterate over each row in the DataFrame
for index, row in df_15.iterrows():
    url = row['url']
    sentiment = get_bbc_textblob_sentiment(url)
    df_15.at[index, 'textblob_Sentiment'] = sentiment

df_15_filtered = df_15.dropna(subset=['textblob_Sentiment'])

df_15_filtered.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2015_seperate_assessed_2.csv', index=False)

In [70]:
df_15_filtered

,Unnamed: 0,title,date,url,player,textblob_Sentiment
232,366,Stephen Curry: NBA three-point record broken b...,2015-16,https://www.bbc.co.uk/sport/basketball/35681271,Stephen Curry,0.325
233,370,Golden State Warriors: Stephen Curry's side ne...,2015-16,https://www.bbc.co.uk/sport/basketball/35976488,Stephen Curry,0.3
235,373,Stephen Curry's Golden State Warriors set new ...,2015-16,http://www.bbc.co.uk/sport/basketball/35640891,Stephen Curry,0.34
243,388,Steph Curry: Warriors star sets NBA three-poin...,2015-16,https://www.bbc.co.uk/sport/basketball/35666842,Stephen Curry,0.325
250,399,Golden State Warriors close in on NBA wins record,2015-16,https://www.bbc.co.uk/sport/basketball/35994800,Stephen Curry,0.245455
...,...,...,...,...,...,...
6048,11514,Rugby World Cup final win defines New Zealand ...,2015-16,http://www.bbc.co.uk/sport/rugby-union/34690513,Michael Carter-Williams,0.140952
6064,11551,Lewis Hamilton on six-man shortlist for world ...,2015-16,https://www.bbc.co.uk/sport/35706859,Michael Carter-Williams,0.228788
6083,11592,Bill Kennedy: NBA referee reveals he is gay af...,2015-16,https://www.bbc.co.uk/sport/basketball/35099861,Rajon Rondo,0.133487
6134,11692,Mohamed Kamara reunites with Finnish club HJK ...,2015-16,http://www.bbc.co.uk/sport/0/football/35737587,Vander Blue,0.164785
6141,11713,Super Bowl 50: Broncos celebrate as Panthers c...,2015-16,https://www.bbc.co.uk/sport/american-football/...,Vander Blue,0.077276

In [71]:

df_16 = df16[(df16['date'] == '2016-17')].copy()
df_16['textblob_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df_16.iterrows():
    url = row['url']
    sentiment = get_bbc_textblob_sentiment(url)
    df_16.at[index, 'textblob_Sentiment'] = sentiment


df_16_filtered = df_16.dropna(subset=['textblob_Sentiment'])

df_16_filtered.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2016_seperate_assessed_2.csv', index=False)

In [5]:

df_17 = df17[(df17['date'] == '2017-18')].copy()
df_17['textblob_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df_17.iterrows():
    url = row['url']
    sentiment = get_bbc_textblob_sentiment(url)
    df_17.at[index, 'textblob_Sentiment'] = sentiment


df_17_filtered = df_17.dropna(subset=['textblob_Sentiment'])

df_17_filtered.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2017_seperate_assessed_2.csv', index=False)

In [6]:

df_18 = df18[(df18['date'] == '2018-19')].copy()
df_18['textblob_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df_18.iterrows():
    url = row['url']
    sentiment = get_bbc_textblob_sentiment(url)
    df_18.at[index, 'textblob_Sentiment'] = sentiment


df_18_filtered = df_18.dropna(subset=['textblob_Sentiment'])

df_18_filtered.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2018_seperate_assessed_2.csv', index=False)

In [7]:

df_19 = df19[(df19['date'] == '2019-20')].copy()
df_19['textblob_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df_19.iterrows():
    url = row['url']
    sentiment = get_bbc_textblob_sentiment(url)
    df_19.at[index, 'textblob_Sentiment'] = sentiment


df_19_filtered = df_19.dropna(subset=['textblob_Sentiment'])

df_19_filtered.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2019_seperate_assessed_2.csv', index=False)

In [ ]:

df_20 = df20[(df20['date'] == '2020-21')].copy()
df_20['textblob_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df_19.iterrows():
    url = row['url']
    sentiment = get_bbc_textblob_sentiment(url)
    df_20.at[index, 'textblob_Sentiment'] = sentiment


df_20_filtered = df_20.dropna(subset=['textblob_Sentiment'])

df_20_filtered.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2020_seperate_assessed_2.csv', index=False)

In [39]:
df20= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2020_season_aggregate.csv')
def get_bbc_textblob_sentiment(url):
    r = requests.get(url)
    soup = BeautifulSoup(r.content, "html.parser") 
    content = soup.find("div", attrs={"class": "gel-layout__item gel-2/3@l"})
    
    if content is None:
        return None

    main_body = content.find_all('p')
    text = ""
    for i in main_body:
        text += i.text
    clean_text = text.replace('\n', ' ').replace('\xa0', '')
    blob = TextBlob(clean_text)
    sentiment = blob.sentiment
    polarity = sentiment.polarity  # Assess sentiment polarity (-1 to 1)
    return polarity

In [42]:
from tqdm import tqdm

df20['textblob_Sentiment'] = None
# Iterate over each row in the DataFrame with tqdm
for index, row in tqdm(df20.iterrows(), total=df20.shape[0], desc='Processing rows'):
    url = row['url']
    sentiment = get_bbc_textblob_sentiment(url)
    df20.at[index, 'textblob_Sentiment'] = sentiment

df_20 = df20.copy()
df_20_filtered = df_20[(df_20['date'] == '2020-21')]
df_20_filtered = df_20_filtered.dropna(subset=['textblob_Sentiment'])

Processing rows:  54%|█████▍    | 2813/5178 [1:54:38<1:36:22,  2.45s/it]

SSLError: HTTPSConnectionPool(host='www.bbc.co.uk', port=443): Max retries exceeded with url: /programmes/m00146x2 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

In [43]:
df_20_filtered

,Unnamed: 0,title,date,url,player,textblob_Sentiment
185,300.0,NBA: LA Lakers lose to Portland as Atlanta Haw...,2020-21,https://www.bbc.co.uk/sport/basketball/55473013,Damian Lillard,0.056967
572,933.0,NBA: Joel Embiid returns from injury in Philad...,2020-21,https://www.bbc.co.uk/sport/basketball/56630066,Luka Dončić,0.155437
585,951.0,NBA: LeBron James stars against Oklahoma City ...,2020-21,https://www.bbc.co.uk/sport/basketball/56022204,Luka Dončić,0.039713
775,1250.0,LeBron James: NBA star's voting rights group s...,2020-21,https://www.bbc.co.uk/news/world-us-canada-563...,LeBron James,-0.013361
864,1428.0,NBA: Joel Embiid stars as Philadelphia 76ers b...,2020-21,https://www.bbc.co.uk/sport/basketball/55643741,Donovan Mitchell,-0.014113
...,...,...,...,...,...,...
5129,NaN,NaN,NaN,NaN,NaN,0.188542
5136,NaN,NaN,NaN,NaN,NaN,0.125097
5266,NaN,NaN,NaN,NaN,NaN,0.006397
5365,NaN,NaN,NaN,NaN,NaN,0.290226
5392,NaN,NaN,NaN,NaN,NaN,0.041835

In [44]:
df_20_filtered = df_20_filtered.dropna(subset=['title'])
df_20_filtered

,Unnamed: 0,title,date,url,player,textblob_Sentiment
185,300.0,NBA: LA Lakers lose to Portland as Atlanta Haw...,2020-21,https://www.bbc.co.uk/sport/basketball/55473013,Damian Lillard,0.056967
572,933.0,NBA: Joel Embiid returns from injury in Philad...,2020-21,https://www.bbc.co.uk/sport/basketball/56630066,Luka Dončić,0.155437
585,951.0,NBA: LeBron James stars against Oklahoma City ...,2020-21,https://www.bbc.co.uk/sport/basketball/56022204,Luka Dončić,0.039713
775,1250.0,LeBron James: NBA star's voting rights group s...,2020-21,https://www.bbc.co.uk/news/world-us-canada-563...,LeBron James,-0.013361
864,1428.0,NBA: Joel Embiid stars as Philadelphia 76ers b...,2020-21,https://www.bbc.co.uk/sport/basketball/55643741,Donovan Mitchell,-0.014113
1069,1786.0,Houston Rockets suffer overtime loss to Portla...,2020-21,https://www.bbc.co.uk/sport/basketball/55458404,CJ McCollum,0.029318
1249,2093.0,"NBA: LA Lakers and LA Clippers win, Boston Cel...",2020-21,https://www.bbc.co.uk/sport/basketball/55615129,Kawhi Leonard,0.155437
1259,2124.0,NBA: Minnesota Timberwolves' Karl-Anthony Town...,2020-21,https://www.bbc.co.uk/sport/basketball/55687220,Kawhi Leonard,0.276
1418,2348.0,LaMelo Ball: Charlotte Hornets rookie becomes ...,2020-21,https://www.bbc.co.uk/sport/basketball/55608161,Nikola Jokić,0.039713
1431,2364.0,NBA: Houston Rockets beat San Antonio Spurs,2020-21,https://www.bbc.co.uk/sport/basketball/55673146,Nikola Jokić,0.333333
1432,2365.0,NBA: LeBron James and Anthony Davis shine as L...,2020-21,https://www.bbc.co.uk/sport/basketball/55556627,Nikola Jokić,0.088131
1617,2674.0,NBA: Kevin Durant leads Brooklyn Nets to victo...,2020-21,https://www.bbc.co.uk/sport/basketball/56060272,Bojan Bogdanović,0.178409
1651,2716.0,NBA round-up: Luka Doncic stars but Dallas Mav...,2020-21,https://www.bbc.co.uk/sport/basketball/55701549,Julius Randle,0.155437
1652,2717.0,NBA: Giannis Antetokounmpo shines as Milwaukee...,2020-21,https://www.bbc.co.uk/sport/basketball/55542453,Julius Randle,0.134402
1935,3239.0,NBA: Fans ejected after argument with LeBron J...,2020-21,https://www.bbc.co.uk/sport/basketball/55899796,Jrue Holiday,0.110459
2051,3414.0,NBA: Jimmy Butler stars as Miami Heat beat Uta...,2020-21,https://www.bbc.co.uk/sport/basketball/56221356,Jimmy Butler,0.160866
2416,4127.0,Leeds United 1-0 Burnley: Patrick Bamford hits...,2020-21,https://www.bbc.co.uk/sport/football/55382725,Harrison Barnes,0.180582
2554,4407.0,Episode 2,2020-21,https://www.bbc.co.uk/programmes/p098hdcr,Joe Harris,0.107614
2929,5207.0,NBA: Utah Jazz beat Philadelphia 76ers to enha...,2020-21,https://www.bbc.co.uk/sport/basketball/56061283,Ben Simmons,0.175
2933,5212.0,NBA All-Star Game: Giannis Antetokounmpo MVP a...,2020-21,https://www.bbc.co.uk/sport/basketball/56318297,Ben Simmons,0.224074
3057,5484.0,NBA: Minnesota Timberwolves' Karl-Anthony Town...,2020-21,https://www.bbc.co.uk/sport/basketball/55687220,Karl-Anthony Towns,0.120096
3953,7234.0,Premiership: Harlequins 24-12 Sale Sharks - Jo...,2020-21,https://www.bbc.co.uk/sport/rugby-union/56111636,Marcus Morris,0.160866
4895,9028.0,Brooklyn Nets beat Orlando Magic for eighth st...,2020-21,https://www.bbc.co.uk/sport/basketball/56207442,Kyrie Irving,0.134402

In [45]:
df_20_filtered.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2020_seperate_assessed_2.csv', index=False)

In [14]:

df_21 = df21[(df21['date'] == '2021-22')].copy()
df_21['textblob_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df_21.iterrows():
    url = row['url']
    sentiment = get_bbc_textblob_sentiment(url)
    df_21.at[index, 'textblob_Sentiment'] = sentiment


df_21_filtered = df_21.dropna(subset=['textblob_Sentiment'])

df_21_filtered.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2021_seperate_assessed_2.csv', index=False)

In [17]:
df_21_filtered.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2021_seperate_assessed_2.csv', index=False)

In [11]:

df_22 = df22[(df22['date'] == '2022-23')].copy()
df_22['textblob_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df_22.iterrows():
    url = row['url']
    sentiment = get_bbc_textblob_sentiment(url)
    df_22.at[index, 'textblob_Sentiment'] = sentiment


df_22_filtered = df_22.dropna(subset=['textblob_Sentiment'])

df_22_filtered.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2022_seperate_assessed_2.csv', index=False)

## NLTK

In [13]:
def assess_sentiment_nltk(text):
    sentiment_analyzer = SentimentIntensityAnalyzer()
    sentiment_scores = sentiment_analyzer.polarity_scores(text)
    score = sentiment_scores['compound']
    return score

def get_bbc_nltk_sentiment(url):
    r = requests.get(url)
    soup = BeautifulSoup(r.content, "html.parser") 
    content = soup.find("div", attrs={"class": "gel-layout__item gel-2/3@l"})
    
    if content is None:
        content = soup.find("td", attrs={"class": "storybody"})
        if content is None:
            return None

    main_body = content.find_all('p')
    text = ""
    for i in main_body:
        text += i.text
    clean_text = text.replace('\n', ' ').replace('\xa0', '')

    score = assess_sentiment_nltk(clean_text)
    return score

In [19]:
df10= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2010_seperate_assessed_3.csv')
df11= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2011_seperate_assessed_3.csv')
df12= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2012_seperate_assessed_3.csv')
df13= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2013_seperate_assessed_3.csv')
df14= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2014_seperate_assessed_3.csv')
df15= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2015_seperate_assessed_3.csv')
df16= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2016_seperate_assessed_3.csv')
df17= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2017_seperate_assessed_3.csv')
df18= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2018_seperate_assessed_3.csv')
df19= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2019_seperate_assessed_3.csv')
#df20= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2020_seperate_assessed_3.csv')
df21= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2021_seperate_assessed_3.csv')
df22= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2022_seperate_assessed_3.csv')

In [21]:
df10['nltk_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df10.iterrows():
    url = row['url']
    sentiment = get_bbc_nltk_sentiment(url)
    df10.at[index, 'nltk_Sentiment'] = sentiment
df10.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2010_seperate_assessed_4.csv', index=False)

In [20]:
df10

,Unnamed: 0,title,date,url,player,textblob_Sentiment,key_words_score
0,225,GB to face US in Olympic warm-up,2010-11,http://news.bbc.co.uk/sport1/hi/other_sports/b...,Kevin Durant,0.123878,1.0
1,503,LeBron James becomes minority stakeholder in L...,2010-11,https://www.bbc.co.uk/sport/football/12994144,LeBron James,0.222059,1.0
2,1533,Team-mates: Lee Mears & David Flatman,2010-11,http://news.bbc.co.uk/sport1/hi/front_page/927...,David Lee,0.209102,0.0
3,1671,Ride the new 2012 Olympic slalom canoe course,2010-11,http://news.bbc.co.uk/sport1/hi/canoeing/92708...,David Lee,0.172389,0.0
4,1689,Fabregas accused referee of taking money - Moyes,2010-11,http://news.bbc.co.uk/sport1/hi/football/teams...,David Lee,0.093581,0.0
...,...,...,...,...,...,...,...
82,15759,Eamon Hughes murder accused admits having knife,2010-11,https://www.bbc.co.uk/news/uk-northern-ireland...,Kevin Martin,-0.375000,0.0
83,15798,"Woman 'thought her father, Eamon Hughes, had b...",2010-11,https://www.bbc.co.uk/news/uk-northern-ireland...,Kevin Martin,0.156950,0.0
84,15823,Man convicted of Eamonn Hughes birthday party ...,2010-11,http://www.bbc.co.uk/news/uk-northern-ireland-...,Kevin Martin,0.238721,0.0
85,15826,Martin summoned back to Ipswich,2010-11,http://news.bbc.co.uk/sport1/hi/football/teams...,Kevin Martin,0.028121,0.8
86,15874,No plan to harm says man accused of Hughes murder,2010-11,https://www.bbc.co.uk/news/uk-northern-ireland...,Kevin Martin,0.216714,0.0

In [22]:
df11['nltk_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df11.iterrows():
    url = row['url']
    sentiment = get_bbc_nltk_sentiment(url)
    df11.at[index, 'nltk_Sentiment'] = sentiment
df11.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2011_seperate_assessed_4.csv', index=False)

In [ ]:
df11

In [23]:
df12['nltk_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df12.iterrows():
    url = row['url']
    sentiment = get_bbc_nltk_sentiment(url)
    df12.at[index, 'nltk_Sentiment'] = sentiment
df12.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2012_seperate_assessed_4.csv', index=False)

In [24]:
df13['nltk_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df13.iterrows():
    url = row['url']
    sentiment = get_bbc_nltk_sentiment(url)
    df13.at[index, 'nltk_Sentiment'] = sentiment
df13.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2013_seperate_assessed_4.csv', index=False)

In [25]:
df14['nltk_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df14.iterrows():
    url = row['url']
    sentiment = get_bbc_nltk_sentiment(url)
    df14.at[index, 'nltk_Sentiment'] = sentiment
df14.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2014_seperate_assessed_4.csv', index=False)

In [26]:
df15['nltk_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df15.iterrows():
    url = row['url']
    sentiment = get_bbc_nltk_sentiment(url)
    df15.at[index, 'nltk_Sentiment'] = sentiment
df15.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2015_seperate_assessed_4.csv', index=False)

In [27]:
df16['nltk_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df16.iterrows():
    url = row['url']
    sentiment = get_bbc_nltk_sentiment(url)
    df16.at[index, 'nltk_Sentiment'] = sentiment
df16.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2016_seperate_assessed_4.csv', index=False)

In [28]:
df17['nltk_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df17.iterrows():
    url = row['url']
    sentiment = get_bbc_nltk_sentiment(url)
    df17.at[index, 'nltk_Sentiment'] = sentiment
df17.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2017_seperate_assessed_4.csv', index=False)

In [30]:
df18['nltk_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df18.iterrows():
    url = row['url']
    sentiment = get_bbc_nltk_sentiment(url)
    df18.at[index, 'nltk_Sentiment'] = sentiment
df18.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2018_seperate_assessed_4.csv', index=False)

In [31]:
df19['nltk_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df19.iterrows():
    url = row['url']
    sentiment = get_bbc_nltk_sentiment(url)
    df19.at[index, 'nltk_Sentiment'] = sentiment
df19.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2019_seperate_assessed_4.csv', index=False)

In [32]:
df19

,Unnamed: 0,title,date,url,player,textblob_Sentiment,key_words_score,nltk_Sentiment
0,352,Kobe Bryant drops Â£3.71m to stay at LA Lakers...,2013-14,https://www.bbc.co.uk/sport/basketball/25095610,Kobe Bryant,0.007670,1.0,0.7427
1,790,LeBron James in talks on David Beckham Miami M...,2013-14,https://www.bbc.co.uk/sport/football/24995887,LeBron James,0.222059,1.0,0.9902
2,1072,LV=Cup: Scarlets 13-7 Gloucester,2013-14,https://www.bbc.co.uk/sport/rugby-union/25885845,James Harden,0.060000,1.0,-0.4215
3,1250,Glasgow 2014: The Jamaican university that cha...,2013-14,https://www.bbc.co.uk/sport/commonwealth-games...,Carmelo Anthony,0.158894,1.0,0.9993
4,1741,Coach Stephen Keshi proud of Nigeria's CHAN ca...,2013-14,https://www.bbc.co.uk/sport/football/26007595,Stephen Curry,0.315657,0.8,0.9935
...,...,...,...,...,...,...,...,...
60,10920,Champions League draw: Man Utd v Bayern Munich...,2013-14,https://www.bbc.co.uk/sport/football/26682665,José Calderón,0.099901,0.4,0.9991
61,10945,Atletico Madrid: Diego Simeone's side are ster...,2013-14,https://www.bbc.co.uk/sport/football/26966304,José Calderón,0.100609,0.4,0.998
62,10955,World Cup 2014: Belgium legends rule out glory...,2013-14,https://www.bbc.co.uk/sport/football/25210495,José Calderón,0.212614,0.4,0.9982
63,10995,"Gossip column: Kroos, Rodriguez, Casillas, Azm...",2013-14,https://www.bbc.co.uk/sport/26965549,José Calderón,0.119570,0.4,0.992
64,11011,Champions League draw: Bayern Munich & PSG fac...,2013-14,https://www.bbc.co.uk/sport/football/26664718,José Calderón,0.150213,0.6,0.9995

In [33]:
df21['nltk_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df21.iterrows():
    url = row['url']
    sentiment = get_bbc_nltk_sentiment(url)
    df21.at[index, 'nltk_Sentiment'] = sentiment
df21.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2021_seperate_assessed_4.csv', index=False)

In [49]:
df21

,Unnamed: 0,title,date,url,player
0,1,NBA: Stephen Curry inspires late Golden State ...,2022-23,https://www.bbc.co.uk/sport/av/basketball/6493...,Stephen Curry
1,2,NBA: Stephen Curry inspires Golden State Warri...,2022-23,https://www.bbc.co.uk/sport/basketball/64930824,Stephen Curry
2,4,NBA: Stephen Curry ruled out indefinitely with...,2022-23,https://www.bbc.co.uk/sport/basketball/64535246,Stephen Curry
3,5,Stephen Curry injured as Golden State Warriors...,2022-23,https://www.bbc.co.uk/sport/basketball/63982850,Stephen Curry
4,8,Stephen Curry: Point guard scores 24 as Golden...,2022-23,https://www.bbc.co.uk/sport/basketball/63686873,Stephen Curry
...,...,...,...,...,...
6424,11843,General election 2019: Conservatives hold both...,2019-20,https://www.bbc.co.uk/news/election-2019-50768643,Justin Jackson
6425,11846,Grays Athletic 2-2 Woking,2005-06,http://news.bbc.co.uk/sport1/hi/football/eng_c...,Justin Jackson
6426,11847,Scarborough 1-1 Woking,2005-06,http://news.bbc.co.uk/sport1/hi/football/eng_c...,Justin Jackson
6427,11848,Stevenage 1-1 Woking,2005-06,http://news.bbc.co.uk/sport1/hi/football/eng_c...,Justin Jackson
6428,11849,Dagenham 1-3 Woking,2005-06,http://news.bbc.co.uk/sport1/hi/football/eng_c...,Justin Jackson

## run the code below later when the former files are updated

In [34]:
df18= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2018_season_aggregate.csv')
df19= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2019_season_aggregate.csv')
df20= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2020_season_aggregate.csv')
df21= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2021_season_aggregate.csv')
df22= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_season_aggregate/bbc_2022_season_aggregate.csv')

In [46]:
df20= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2020_seperate_assessed_3.csv')

In [47]:
df20['nltk_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df20.iterrows():
    url = row['url']
    sentiment = get_bbc_nltk_sentiment(url)
    df20.at[index, 'nltk_Sentiment'] = sentiment
df20.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2020_seperate_assessed_4.csv', index=False)

In [48]:
df20

,Unnamed: 0,title,date,url,player,textblob_Sentiment,key_words_score,nltk_Sentiment
0,300.0,NBA: LA Lakers lose to Portland as Atlanta Haw...,2020-21,https://www.bbc.co.uk/sport/basketball/55473013,Damian Lillard,0.056967,1.0,0.9913
1,933.0,NBA: Joel Embiid returns from injury in Philad...,2020-21,https://www.bbc.co.uk/sport/basketball/56630066,Luka Dončić,0.155437,0.6,0.9702
2,951.0,NBA: LeBron James stars against Oklahoma City ...,2020-21,https://www.bbc.co.uk/sport/basketball/56022204,Luka Dončić,0.039713,0.6,0.991
3,1250.0,LeBron James: NBA star's voting rights group s...,2020-21,https://www.bbc.co.uk/news/world-us-canada-563...,LeBron James,-0.013361,0.0,None
4,1428.0,NBA: Joel Embiid stars as Philadelphia 76ers b...,2020-21,https://www.bbc.co.uk/sport/basketball/55643741,Donovan Mitchell,-0.014113,1.0,0.9628
5,1786.0,Houston Rockets suffer overtime loss to Portla...,2020-21,https://www.bbc.co.uk/sport/basketball/55458404,CJ McCollum,0.029318,1.0,-0.3818
6,2093.0,"NBA: LA Lakers and LA Clippers win, Boston Cel...",2020-21,https://www.bbc.co.uk/sport/basketball/55615129,Kawhi Leonard,0.155437,1.0,0.9641
7,2124.0,NBA: Minnesota Timberwolves' Karl-Anthony Town...,2020-21,https://www.bbc.co.uk/sport/basketball/55687220,Kawhi Leonard,0.276000,1.0,0.9627
8,2348.0,LaMelo Ball: Charlotte Hornets rookie becomes ...,2020-21,https://www.bbc.co.uk/sport/basketball/55608161,Nikola Jokić,0.039713,0.8,-0.6563
9,2364.0,NBA: Houston Rockets beat San Antonio Spurs,2020-21,https://www.bbc.co.uk/sport/basketball/55673146,Nikola Jokić,0.333333,0.6,0.979
10,2365.0,NBA: LeBron James and Anthony Davis shine as L...,2020-21,https://www.bbc.co.uk/sport/basketball/55556627,Nikola Jokić,0.088131,0.6,0.9239
11,2674.0,NBA: Kevin Durant leads Brooklyn Nets to victo...,2020-21,https://www.bbc.co.uk/sport/basketball/56060272,Bojan Bogdanović,0.178409,0.8,0.9847
12,2716.0,NBA round-up: Luka Doncic stars but Dallas Mav...,2020-21,https://www.bbc.co.uk/sport/basketball/55701549,Julius Randle,0.155437,1.0,-0.5719
13,2717.0,NBA: Giannis Antetokounmpo shines as Milwaukee...,2020-21,https://www.bbc.co.uk/sport/basketball/55542453,Julius Randle,0.134402,1.0,0.9718
14,3239.0,NBA: Fans ejected after argument with LeBron J...,2020-21,https://www.bbc.co.uk/sport/basketball/55899796,Jrue Holiday,0.110459,1.0,0.9844
15,3414.0,NBA: Jimmy Butler stars as Miami Heat beat Uta...,2020-21,https://www.bbc.co.uk/sport/basketball/56221356,Jimmy Butler,0.160866,0.8,0.7086
16,4127.0,Leeds United 1-0 Burnley: Patrick Bamford hits...,2020-21,https://www.bbc.co.uk/sport/football/55382725,Harrison Barnes,0.180582,0.8,0.9982
17,4407.0,Episode 2,2020-21,https://www.bbc.co.uk/programmes/p098hdcr,Joe Harris,0.107614,0.0,None
18,5207.0,NBA: Utah Jazz beat Philadelphia 76ers to enha...,2020-21,https://www.bbc.co.uk/sport/basketball/56061283,Ben Simmons,0.175000,1.2,0.9731
19,5212.0,NBA All-Star Game: Giannis Antetokounmpo MVP a...,2020-21,https://www.bbc.co.uk/sport/basketball/56318297,Ben Simmons,0.224074,1.4,0.9981
20,5484.0,NBA: Minnesota Timberwolves' Karl-Anthony Town...,2020-21,https://www.bbc.co.uk/sport/basketball/55687220,Karl-Anthony Towns,0.120096,0.6,0.9627
21,7234.0,Premiership: Harlequins 24-12 Sale Sharks - Jo...,2020-21,https://www.bbc.co.uk/sport/rugby-union/56111636,Marcus Morris,0.160866,1.0,0.9695
22,9028.0,Brooklyn Nets beat Orlando Magic for eighth st...,2020-21,https://www.bbc.co.uk/sport/basketball/56207442,Kyrie Irving,0.134402,1.0,0.9344

In [37]:
df22= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2022_seperate_assessed_3.csv')

In [38]:
df22['nltk_Sentiment'] = None
# Iterate over each row in the DataFrame
for index, row in df22.iterrows():
    url = row['url']
    sentiment = get_bbc_nltk_sentiment(url)
    df22.at[index, 'nltk_Sentiment'] = sentiment
df22.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2022_seperate_assessed_4.csv', index=False)

,Unnamed: 0,title,date,url,player,textblob_Sentiment,key_words_score,nltk_Sentiment
0,8,NBA: Ja Morant inspires Memphis Grizzlies win ...,2022-23,https://www.bbc.co.uk/sport/basketball/63355733,Trae Young,0.130700,1.2,0.8704
1,25,NBA on the BBC: The big questions as NBA retur...,2022-23,https://www.bbc.co.uk/sport/basketball/64722489,Trae Young,0.063053,0.8,0.9968
2,28,Bellator 292: Michael 'Venom' Page to face Goi...,2022-23,https://www.bbc.co.uk/sport/mixed-martial-arts...,Trae Young,0.262333,0.8,0.9259
3,36,Super Bowl 57: Patrick Mahomes wins second tit...,2022-23,https://www.bbc.co.uk/sport/american-football/...,Trae Young,0.173912,0.8,0.9995
4,66,Tom Brady retires 'for good' after 23 seasons ...,2022-23,https://www.bbc.co.uk/sport/american-football/...,Trae Young,0.155320,0.6,0.9989
...,...,...,...,...,...,...,...,...
741,11368,NBA: Dallas Mavericks stars Luka Doncic and Ky...,2022-23,https://www.bbc.co.uk/sport/basketball/64833608,Jaylen Hoard,0.141611,0.8,0.9872
742,11369,NBA on the BBC: The big questions as NBA retur...,2022-23,https://www.bbc.co.uk/sport/basketball/64722489,Jaylen Hoard,0.063053,0.8,0.9968
743,11391,NFL week eight review: MVP shouts for Josh All...,2022-23,https://www.bbc.co.uk/sport/american-football/...,Derrick Walton,0.180487,0.8,0.996
744,11398,Super Bowl 57: Kansas City Chiefs fight back t...,2022-23,https://www.bbc.co.uk/sport/american-football/...,Derrick Walton,0.211105,0.6,0.9988
745,11413,NFL London: Russell Wilson under scrutiny as D...,2022-23,https://www.bbc.co.uk/sport/american-football/...,Derrick Walton,0.110752,0.8,0.9936

In [52]:
df21= pd.read_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/bbc_news_seperate/bbc_2021_seperate_assessed_FN.csv')

In [54]:
df_1 = df21[:200]
from tqdm import tqdm
df_1['nltk_Sentiment'] = None
progress_bar = tqdm(total=len(df_1), desc="Processing Rows")

for index, row in df_1.iterrows():
    url = row['url']
    sentiment = get_bbc_nltk_sentiment(url)
    df_1.at[index, 'nltk_Sentiment'] = sentiment
    progress_bar.update(1)

progress_bar.close()

/var/folders/9g/wg6kygl97c58z_h6ljqdr8g00000gn/T/ipykernel_94369/714898325.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1['nltk_Sentiment'] = None
Processing Rows: 100%|██████████| 200/200 [09:17<00:00,  2.79s/it]

In [55]:
df_2 = df21[200:400]
from tqdm import tqdm
df_2['nltk_Sentiment'] = None
progress_bar = tqdm(total=len(df_2), desc="Processing Rows")

for index, row in df_2.iterrows():
    url = row['url']
    sentiment = get_bbc_nltk_sentiment(url)
    df_2.at[index, 'nltk_Sentiment'] = sentiment
    progress_bar.update(1)

progress_bar.close()

/var/folders/9g/wg6kygl97c58z_h6ljqdr8g00000gn/T/ipykernel_94369/128888299.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2['nltk_Sentiment'] = None
Processing Rows: 100%|██████████| 200/200 [12:23<00:00,  3.72s/it]

In [56]:
df_3 = df21[400:600]
from tqdm import tqdm
df_3['nltk_Sentiment'] = None
progress_bar = tqdm(total=len(df_3), desc="Processing Rows")

for index, row in df_3.iterrows():
    url = row['url']
    sentiment = get_bbc_nltk_sentiment(url)
    df_3.at[index, 'nltk_Sentiment'] = sentiment
    progress_bar.update(1)

progress_bar.close()

/var/folders/9g/wg6kygl97c58z_h6ljqdr8g00000gn/T/ipykernel_94369/4233264255.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_3['nltk_Sentiment'] = None
Processing Rows: 100%|██████████| 200/200 [08:12<00:00,  2.46s/it]

In [58]:
df_4= df21[600:800]
from tqdm import tqdm
df_4['nltk_Sentiment'] = None
progress_bar = tqdm(total=len(df_4), desc="Processing Rows")

for index, row in df_4.iterrows():
    url = row['url']
    sentiment = get_bbc_nltk_sentiment(url)
    df_4.at[index, 'nltk_Sentiment'] = sentiment
    progress_bar.update(1)

progress_bar.close()

/var/folders/9g/wg6kygl97c58z_h6ljqdr8g00000gn/T/ipykernel_94369/836992701.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_4['nltk_Sentiment'] = None
Processing Rows: 100%|██████████| 200/200 [10:28<00:00,  3.14s/it]

In [57]:
df_5 = df21[800:]
from tqdm import tqdm
df_5['nltk_Sentiment'] = None
progress_bar = tqdm(total=len(df_5), desc="Processing Rows")

for index, row in df_5.iterrows():
    url = row['url']
    sentiment = get_bbc_nltk_sentiment(url)
    df_5.at[index, 'nltk_Sentiment'] = sentiment
    progress_bar.update(1)

progress_bar.close()

/var/folders/9g/wg6kygl97c58z_h6ljqdr8g00000gn/T/ipykernel_94369/1077805178.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_5['nltk_Sentiment'] = None
Processing Rows: 100%|██████████| 224/224 [13:14<00:00,  3.55s/it]