In [1]:
import pandas as pd

# Importing Data

## Importing Box Score Data

In [2]:
df_all = pd.read_csv("../Data/merged_player_data_2010_2023.csv") 
df_all.drop(df_all.columns[df_all.columns.str.contains("Unnamed")], axis = 1, inplace = True) 
df_all["year"] = df_all["year"].apply(lambda x: int(x[:4])) 
df_all.drop("positions", axis = 1, inplace = True)
df_all

,year,name,minutes_played,games_played,points,team,age,assists,attempted_field_goals,attempted_free_throws,...,defensive_rebounds,games_started,made_field_goals,made_free_throws,made_three_point_field_goals,offensive_rebounds,personal_fouls,slug,steals,turnovers
0,2023,Jayson Tatum,2508,67,2008,BOSTON CELTICS,24,317,1424,568,...,524,67,651,488,218,73,144,tatumja01,68,198
1,2023,Joel Embiid,2030,58,1946,PHILADELPHIA 76ERS,28,238,1186,691,...,490,58,647,591,61,105,186,embiijo01,62,201
2,2023,Shai Gilgeous-Alexander,2135,60,1884,OKLAHOMA CITY THUNDER,24,330,1222,646,...,233,60,624,584,52,54,163,gilgesh01,102,173
3,2023,Luka Dončić,2068,57,1879,DALLAS MAVERICKS,23,458,1257,629,...,443,57,629,463,158,48,148,doncilu01,83,209
4,2023,Julius Randle,2623,73,1869,NEW YORK KNICKS,28,299,1372,515,...,604,73,633,391,212,139,223,randlju01,47,208
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1428,2010,Allen Iverson,798,25,348,PHILADELPHIA 76ERS,34,102,290,119,...,60,24,121,98,8,15,43,iversal01,18,57
1429,2010,Marcus Camby,718,23,162,PORTLAND TRAIL BLAZERS,35,35,145,31,...,172,23,72,18,0,83,56,cambyma01,26,27
1430,2010,Stephen Jackson,300,9,149,GOLDEN STATE WARRIORS,31,42,133,37,...,29,9,56,26,11,6,16,jacksst02,14,26
1431,2010,Earl Barron,232,7,82,NEW YORK KNICKS,28,8,68,29,...,46,6,30,22,0,31,24,barroea01,4,11
1432,2010,Raja Bell,157,5,60,CHARLOTTE BOBCATS,33,10,55,3,...,16,5,24,3,9,5,13,bellra01,4,5

In [3]:
targets = ["year", "slug", "name", "team", "age", "games_played"] 
targets = targets[::-1]
cols = list(df_all.columns)
for col in targets: 
    cols.insert(0, cols.pop(cols.index(col))) 
df_all = df_all.loc[:, cols]
df_all.rename(columns = {"year": "season"}, inplace = True)
df_all

,season,slug,name,team,age,games_played,minutes_played,points,assists,attempted_field_goals,...,blocks,defensive_rebounds,games_started,made_field_goals,made_free_throws,made_three_point_field_goals,offensive_rebounds,personal_fouls,steals,turnovers
0,2023,tatumja01,Jayson Tatum,BOSTON CELTICS,24,67,2508,2008,317,1424,...,50,524,67,651,488,218,73,144,68,198
1,2023,embiijo01,Joel Embiid,PHILADELPHIA 76ERS,28,58,2030,1946,238,1186,...,102,490,58,647,591,61,105,186,62,201
2,2023,gilgesh01,Shai Gilgeous-Alexander,OKLAHOMA CITY THUNDER,24,60,2135,1884,330,1222,...,60,233,60,624,584,52,54,163,102,173
3,2023,doncilu01,Luka Dončić,DALLAS MAVERICKS,23,57,2068,1879,458,1257,...,28,443,57,629,463,158,48,148,83,209
4,2023,randlju01,Julius Randle,NEW YORK KNICKS,28,73,2623,1869,299,1372,...,19,604,73,633,391,212,139,223,47,208
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1428,2010,iversal01,Allen Iverson,PHILADELPHIA 76ERS,34,25,798,348,102,290,...,2,60,24,121,98,8,15,43,18,57
1429,2010,cambyma01,Marcus Camby,PORTLAND TRAIL BLAZERS,35,23,718,162,35,145,...,47,172,23,72,18,0,83,56,26,27
1430,2010,jacksst02,Stephen Jackson,GOLDEN STATE WARRIORS,31,9,300,149,42,133,...,6,29,9,56,26,11,6,16,14,26
1431,2010,barroea01,Earl Barron,NEW YORK KNICKS,28,7,232,82,8,68,...,4,46,6,30,22,0,31,24,4,11
1432,2010,bellra01,Raja Bell,CHARLOTTE BOBCATS,33,5,157,60,10,55,...,2,16,5,24,3,9,5,13,4,5

## Importing Advanced Statistics

In [4]:
df_advanced = pd.read_csv("../Data/merged_advanced_player_data_2010_2023.csv") 
df_advanced.drop(df_advanced.columns[df_advanced.columns.str.contains("Unnamed")], axis = 1, inplace = True) 
df_advanced["year"] = df_advanced["year"].apply(lambda x: int(x[:4])) 
df_advanced.drop(["positions", "minutes_played", "is_combined_totals"], axis = 1, inplace = True)
df_advanced

,year,name,age,assist_percentage,block_percentage,box_plus_minus,defensive_box_plus_minus,defensive_rebound_percentage,defensive_win_shares,free_throw_attempt_rate,...,steal_percentage,team,three_point_attempt_rate,total_rebound_percentage,true_shooting_percentage,turnover_percentage,usage_percentage,value_over_replacement_player,win_shares,win_shares_per_48_minutes
0,2012,LeBron James,27,33.6,1.7,10.9,2.7,19.7,4.5,0.429,...,2.6,MIAMI HEAT,0.127,12.6,0.605,13.3,32.0,7.6,14.5,0.298
1,2012,Kyrylo Fesenko,25,9.5,0.0,8.4,3.6,46.0,0.1,1.200,...,6.2,INDIANA PACERS,0.000,29.8,0.524,0.0,20.4,0.0,0.1,0.374
2,2012,Chris Paul,26,43.8,0.2,9.2,2.4,9.4,2.3,0.339,...,3.8,LOS ANGELES CLIPPERS,0.239,5.8,0.581,10.8,24.3,6.1,12.7,0.278
3,2012,Dwyane Wade,30,27.3,3.1,7.9,1.9,11.6,2.9,0.355,...,2.7,MIAMI HEAT,0.067,8.7,0.559,11.8,31.3,4.0,7.7,0.227
4,2012,Kevin Durant,23,17.5,2.2,7.0,0.8,20.4,3.7,0.386,...,1.8,OKLAHOMA CITY THUNDER,0.265,11.8,0.610,14.0,31.3,5.8,12.2,0.230
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8025,2023,Frank Jackson,24,22.8,0.0,-22.2,-9.8,21.5,0.0,0.000,...,0.0,UTAH JAZZ,0.333,21.7,0.000,0.0,25.1,0.0,0.0,-0.374
8026,2023,Jamaree Bouyea,23,0.0,0.0,-17.8,-1.7,17.8,0.0,0.000,...,0.0,WASHINGTON WIZARDS,1.000,9.3,0.000,0.0,7.3,0.0,0.0,-0.149
8027,2023,Marko Simonovic,23,0.0,0.0,-21.7,-5.8,0.0,0.0,0.000,...,0.0,CHICAGO BULLS,1.000,0.0,0.000,0.0,8.8,0.0,0.0,-0.201
8028,2023,Deonte Burton,29,0.0,0.0,-24.7,-10.0,0.0,0.0,0.000,...,0.0,SACRAMENTO KINGS,0.500,0.0,0.000,0.0,14.3,0.0,0.0,-0.349
8029,2023,Alondes Williams,23,0.0,0.0,-26.6,-5.3,21.9,0.0,0.000,...,0.0,BROOKLYN NETS,0.000,11.3,0.000,100.0,17.8,0.0,-0.1,-0.517

In [5]:
targets = ["year", "slug", "name", "team", "age", "games_played"] 
targets = targets[::-1]
cols = list(df_advanced.columns)
for col in targets: 
    cols.insert(0, cols.pop(cols.index(col))) 
df_advanced = df_advanced.loc[:, cols]
df_advanced.rename(columns = {"year": "season"}, inplace = True)
df_advanced

,season,slug,name,team,age,games_played,assist_percentage,block_percentage,box_plus_minus,defensive_box_plus_minus,...,player_efficiency_rating,steal_percentage,three_point_attempt_rate,total_rebound_percentage,true_shooting_percentage,turnover_percentage,usage_percentage,value_over_replacement_player,win_shares,win_shares_per_48_minutes
0,2012,jamesle01,LeBron James,MIAMI HEAT,27,62,33.6,1.7,10.9,2.7,...,30.7,2.6,0.127,12.6,0.605,13.3,32.0,7.6,14.5,0.298
1,2012,fesenky01,Kyrylo Fesenko,INDIANA PACERS,25,3,9.5,0.0,8.4,3.6,...,29.8,6.2,0.000,29.8,0.524,0.0,20.4,0.0,0.1,0.374
2,2012,paulch01,Chris Paul,LOS ANGELES CLIPPERS,26,60,43.8,0.2,9.2,2.4,...,27.0,3.8,0.239,5.8,0.581,10.8,24.3,6.1,12.7,0.278
3,2012,wadedw01,Dwyane Wade,MIAMI HEAT,30,49,27.3,3.1,7.9,1.9,...,26.3,2.7,0.067,8.7,0.559,11.8,31.3,4.0,7.7,0.227
4,2012,duranke01,Kevin Durant,OKLAHOMA CITY THUNDER,23,66,17.5,2.2,7.0,0.8,...,26.2,1.8,0.265,11.8,0.610,14.0,31.3,5.8,12.2,0.230
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8025,2023,jacksfr01,Frank Jackson,UTAH JAZZ,24,1,22.8,0.0,-22.2,-9.8,...,-6.8,0.0,0.333,21.7,0.000,0.0,25.1,0.0,0.0,-0.374
8026,2023,bouyeja01,Jamaree Bouyea,WASHINGTON WIZARDS,23,1,0.0,0.0,-17.8,-1.7,...,-7.0,0.0,1.000,9.3,0.000,0.0,7.3,0.0,0.0,-0.149
8027,2023,simonma01,Marko Simonovic,CHICAGO BULLS,23,3,0.0,0.0,-21.7,-5.8,...,-10.8,0.0,1.000,0.0,0.000,0.0,8.8,0.0,0.0,-0.201
8028,2023,burtode02,Deonte Burton,SACRAMENTO KINGS,29,2,0.0,0.0,-24.7,-10.0,...,-12.6,0.0,0.500,0.0,0.000,0.0,14.3,0.0,0.0,-0.349
8029,2023,willial06,Alondes Williams,BROOKLYN NETS,23,1,0.0,0.0,-26.6,-5.3,...,-20.9,0.0,0.000,11.3,0.000,100.0,17.8,0.0,-0.1,-0.517

# Clean up duplicates due to trades

In [6]:
id_cols = df_all.iloc[:, :5].columns 
stats_cols = df_all.iloc[:, 5:].columns 
df_group = df_all.groupby(["season", "slug", "name"]) 
df_str = df_group.agg({"team": lambda x: ", ".join(x), "age": "min"})
df_int = df_group[stats_cols].agg("sum")
df_no_dup = df_str.merge(df_int, left_index = True, right_index = True).reset_index()
df_no_dup

,season,slug,name,team,age,games_played,minutes_played,points,assists,attempted_field_goals,...,blocks,defensive_rebounds,games_started,made_field_goals,made_free_throws,made_three_point_field_goals,offensive_rebounds,personal_fouls,steals,turnovers
0,2010,aldrila01,LaMarcus Aldridge,PORTLAND TRAIL BLAZERS,24,78,2922,1393,160,1169,...,48,435,78,579,230,5,192,231,67,104
1,2010,allenra02,Ray Allen,BOSTON CELTICS,34,80,2819,1304,210,973,...,25,208,80,464,231,145,45,182,64,129
2,2010,anthoca01,Carmelo Anthony,DENVER NUGGETS,25,69,2634,1943,222,1502,...,30,302,69,688,508,59,152,225,88,209
3,2010,arenagi01,Gilbert Arenas,WASHINGTON WIZARDS,28,32,1169,722,230,616,...,9,116,32,253,153,63,17,95,41,117
4,2010,arizatr01,Trevor Ariza,HOUSTON ROCKETS,24,72,2629,1072,276,999,...,40,325,71,394,148,136,78,162,126,161
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1372,2023,washipj01,P.J. Washington,CHARLOTTE HORNETS,24,68,2235,1026,159,884,...,77,263,68,388,115,135,67,182,61,101
1373,2023,westbru01,Russell Westbrook,LOS ANGELES CLIPPERS,34,11,334,144,86,127,...,3,43,11,57,21,9,14,26,14,42
1374,2023,wiggian01,Andrew Wiggins,GOLDEN STATE WARRIORS,27,37,1190,633,85,529,...,28,125,37,250,44,89,61,107,45,48
1375,2023,willizi01,Zion Williamson,NEW ORLEANS PELICANS,22,29,956,754,133,469,...,16,144,29,285,177,7,58,65,32,99
1376,2023,youngtr01,Trae Young,ATLANTA HAWKS,24,64,2232,1711,642,1255,...,9,146,64,545,480,141,52,94,72,261

In [7]:
id_cols = df_advanced.iloc[:, :5].columns 
stats_cols = df_advanced.iloc[:, 5:].columns 
df_group = df_advanced.groupby(["season", "slug", "name"]) 
df_str = df_group.agg({"team": lambda x: ", ".join(x), "age": "min"})
df_int = df_group[stats_cols].agg("sum")
df_no_dup_advanced = df_str.merge(df_int, left_index = True, right_index = True).reset_index()
df_no_dup_advanced

,season,slug,name,team,age,games_played,assist_percentage,block_percentage,box_plus_minus,defensive_box_plus_minus,...,player_efficiency_rating,steal_percentage,three_point_attempt_rate,total_rebound_percentage,true_shooting_percentage,turnover_percentage,usage_percentage,value_over_replacement_player,win_shares,win_shares_per_48_minutes
0,2010,afflaar01,Arron Afflalo,DENVER NUGGETS,24,82,9.3,1.0,-0.4,-0.2,...,10.9,1.0,0.426,6.5,0.576,10.5,14.0,0.9,4.3,0.092
1,2010,ajincal01,Alexis Ajinça,CHARLOTTE BOBCATS,21,6,0.0,2.7,-5.3,1.0,...,6.3,1.8,0.000,8.0,0.479,16.1,19.3,0.0,0.0,-0.013
2,2010,aldrila01,LaMarcus Aldridge,PORTLAND TRAIL BLAZERS,24,78,9.9,1.3,1.2,-0.2,...,18.2,1.3,0.014,13.3,0.535,7.4,22.9,2.3,8.8,0.145
3,2010,alexajo01,Joe Alexander,CHICAGO BULLS,23,8,9.3,2.6,-8.3,0.9,...,2.8,1.8,0.167,9.6,0.273,0.0,11.3,0.0,0.0,0.030
4,2010,allenma01,Malik Allen,DENVER NUGGETS,31,51,5.1,0.8,-5.7,-1.0,...,5.9,1.2,0.052,10.4,0.431,15.3,14.0,-0.4,0.1,0.009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7036,2023,youngth01,Thaddeus Young,TORONTO RAPTORS,34,54,13.0,0.6,0.0,1.8,...,14.1,3.4,0.172,11.8,0.573,16.7,13.5,0.4,1.8,0.107
7037,2023,youngtr01,Trae Young,ATLANTA HAWKS,24,64,42.6,0.3,3.6,-1.8,...,22.5,1.5,0.333,4.8,0.573,14.9,33.1,3.2,5.9,0.128
7038,2023,yurtsom01,Omer Yurtseven,MIAMI HEAT,24,5,0.0,3.0,-8.7,-2.5,...,9.4,1.5,0.125,13.7,0.507,10.1,12.8,-0.1,0.1,0.077
7039,2023,zelleco01,Cody Zeller,MIAMI HEAT,30,10,6.7,3.1,-4.3,-0.5,...,13.1,0.8,0.034,15.7,0.601,17.0,16.0,-0.1,0.3,0.124
7040,2023,zubaciv01,Ivica Zubac,LOS ANGELES CLIPPERS,25,66,5.2,4.0,-1.1,0.2,...,16.3,0.6,0.004,19.5,0.650,16.8,14.5,0.5,5.7,0.143

# Per game Data

In [8]:
df_id = df_no_dup.iloc[:, :6]
df_per_game = df_no_dup.iloc[:, 6:].div(df_no_dup["games_played"], axis = 0) 
df_per_game = df_id.merge(df_per_game, left_index = True, right_index = True)
df_per_game

,season,slug,name,team,age,games_played,minutes_played,points,assists,attempted_field_goals,...,blocks,defensive_rebounds,games_started,made_field_goals,made_free_throws,made_three_point_field_goals,offensive_rebounds,personal_fouls,steals,turnovers
0,2010,aldrila01,LaMarcus Aldridge,PORTLAND TRAIL BLAZERS,24,78,37.461538,17.858974,2.051282,14.987179,...,0.615385,5.576923,1.000000,7.423077,2.948718,0.064103,2.461538,2.961538,0.858974,1.333333
1,2010,allenra02,Ray Allen,BOSTON CELTICS,34,80,35.237500,16.300000,2.625000,12.162500,...,0.312500,2.600000,1.000000,5.800000,2.887500,1.812500,0.562500,2.275000,0.800000,1.612500
2,2010,anthoca01,Carmelo Anthony,DENVER NUGGETS,25,69,38.173913,28.159420,3.217391,21.768116,...,0.434783,4.376812,1.000000,9.971014,7.362319,0.855072,2.202899,3.260870,1.275362,3.028986
3,2010,arenagi01,Gilbert Arenas,WASHINGTON WIZARDS,28,32,36.531250,22.562500,7.187500,19.250000,...,0.281250,3.625000,1.000000,7.906250,4.781250,1.968750,0.531250,2.968750,1.281250,3.656250
4,2010,arizatr01,Trevor Ariza,HOUSTON ROCKETS,24,72,36.513889,14.888889,3.833333,13.875000,...,0.555556,4.513889,0.986111,5.472222,2.055556,1.888889,1.083333,2.250000,1.750000,2.236111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1372,2023,washipj01,P.J. Washington,CHARLOTTE HORNETS,24,68,32.867647,15.088235,2.338235,13.000000,...,1.132353,3.867647,1.000000,5.705882,1.691176,1.985294,0.985294,2.676471,0.897059,1.485294
1373,2023,westbru01,Russell Westbrook,LOS ANGELES CLIPPERS,34,11,30.363636,13.090909,7.818182,11.545455,...,0.272727,3.909091,1.000000,5.181818,1.909091,0.818182,1.272727,2.363636,1.272727,3.818182
1374,2023,wiggian01,Andrew Wiggins,GOLDEN STATE WARRIORS,27,37,32.162162,17.108108,2.297297,14.297297,...,0.756757,3.378378,1.000000,6.756757,1.189189,2.405405,1.648649,2.891892,1.216216,1.297297
1375,2023,willizi01,Zion Williamson,NEW ORLEANS PELICANS,22,29,32.965517,26.000000,4.586207,16.172414,...,0.551724,4.965517,1.000000,9.827586,6.103448,0.241379,2.000000,2.241379,1.103448,3.413793
1376,2023,youngtr01,Trae Young,ATLANTA HAWKS,24,64,34.875000,26.734375,10.031250,19.609375,...,0.140625,2.281250,1.000000,8.515625,7.500000,2.203125,0.812500,1.468750,1.125000,4.078125

# Create efficiency stats

In [9]:
df_per_game.columns

Index(['season', 'slug', 'name', 'team', 'age', 'games_played',
       'minutes_played', 'points', 'assists', 'attempted_field_goals',
       'attempted_free_throws', 'attempted_three_point_field_goals', 'blocks',
       'defensive_rebounds', 'games_started', 'made_field_goals',
       'made_free_throws', 'made_three_point_field_goals',
       'offensive_rebounds', 'personal_fouls', 'steals', 'turnovers'],
      dtype='object')

In [10]:
df_advanced.columns

Index(['season', 'slug', 'name', 'team', 'age', 'games_played',
       'assist_percentage', 'block_percentage', 'box_plus_minus',
       'defensive_box_plus_minus', 'defensive_rebound_percentage',
       'defensive_win_shares', 'free_throw_attempt_rate',
       'offensive_box_plus_minus', 'offensive_rebound_percentage',
       'offensive_win_shares', 'player_efficiency_rating', 'steal_percentage',
       'three_point_attempt_rate', 'total_rebound_percentage',
       'true_shooting_percentage', 'turnover_percentage', 'usage_percentage',
       'value_over_replacement_player', 'win_shares',
       'win_shares_per_48_minutes'],
      dtype='object')

## Create %games_played

In [11]:
df_num_games_2020 = pd.read_csv("../Data/num_games_2020.csv") 
df_num_games_2023 = pd.read_csv("../Data/num_games_2023.csv")

In [12]:
df_num_games_2020 = df_num_games_2020.iloc[1:, 1:3] 
df_num_games_2020.rename(columns = {"Unnamed: 1": "team", "Unnamed: 2": "record"}, inplace = True) 
df_num_games_2020["total_games"] = df_num_games_2020["record"].apply(lambda x: int(x.split("-")[0]) + int(x.split("-")[1])) 
df_num_games_2020.drop("record", axis = 1, inplace = True) 
df_num_games_2020["team"] = df_num_games_2020["team"].apply(lambda x: x.upper())
df_num_games_2020

                      team  total_games
1          MILWAUKEE BUCKS           73
2          TORONTO RAPTORS           72
3       LOS ANGELES LAKERS           71
4     LOS ANGELES CLIPPERS           72
5           BOSTON CELTICS           72
6           DENVER NUGGETS           73
7           INDIANA PACERS           73
8          HOUSTON ROCKETS           72
9               MIAMI HEAT           73
10   OKLAHOMA CITY THUNDER           72
11               UTAH JAZZ           72
12        DALLAS MAVERICKS           75
13      PHILADELPHIA 76ERS           73
14           BROOKLYN NETS           72
15  PORTLAND TRAIL BLAZERS           74
16       MEMPHIS GRIZZLIES           73
17            PHOENIX SUNS           73
18           ORLANDO MAGIC           73
19       SAN ANTONIO SPURS           71
20        SACRAMENTO KINGS           72
21    NEW ORLEANS PELICANS           72
22      WASHINGTON WIZARDS           72
23       CHARLOTTE HORNETS           65
24           CHICAGO BULLS           65
25         NEW YORK KNICKS           66
26           ATLANTA HAWKS           67
27         DETROIT PISTONS           66
28     CLEVELAND CAVALIERS           65
29  MINNESOTA TIMBERWOLVES           64
30   GOLDEN STATE WARRIORS           65

In [13]:
df_num_games_2023 = df_num_games_2023.iloc[1:, 1:3] 
df_num_games_2023.rename(columns = {"Unnamed: 1": "team", "Unnamed: 2": "record"}, inplace = True) 
df_num_games_2023["total_games"] = df_num_games_2023["record"].apply(lambda x: int(x.split("-")[0]) + int(x.split("-")[1])) 
df_num_games_2023.drop("record", axis = 1, inplace = True) 
df_num_games_2023["team"] = df_num_games_2023["team"].apply(lambda x: x.upper())
df_num_games_2023

                      team  total_games
1          MILWAUKEE BUCKS           72
2           BOSTON CELTICS           73
3           DENVER NUGGETS           73
4       PHILADELPHIA 76ERS           72
5      CLEVELAND CAVALIERS           74
6        MEMPHIS GRIZZLIES           72
7         SACRAMENTO KINGS           72
8          NEW YORK KNICKS           74
9               MIAMI HEAT           74
10           BROOKLYN NETS           72
11   GOLDEN STATE WARRIORS           74
12    LOS ANGELES CLIPPERS           73
13            PHOENIX SUNS           72
14  MINNESOTA TIMBERWOLVES           74
15           ATLANTA HAWKS           73
16        DALLAS MAVERICKS           73
17      LOS ANGELES LAKERS           73
18   OKLAHOMA CITY THUNDER           72
19    NEW ORLEANS PELICANS           72
20         TORONTO RAPTORS           73
21               UTAH JAZZ           72
22           CHICAGO BULLS           72
23          INDIANA PACERS           73
24  PORTLAND TRAIL BLAZERS           72
25      WASHINGTON WIZARDS           73
26           ORLANDO MAGIC           73
27       CHARLOTTE HORNETS           73
28       SAN ANTONIO SPURS           73
29         HOUSTON ROCKETS           73
30         DETROIT PISTONS           73

In [14]:
def fill_total_games(df): 
    if df["season"] == 2021: 
        return 72 
    elif df["season"] == 2012: 
        return 66
    elif df["season"] == 2020: 
        try: 
            return df_num_games_2020[df_num_games_2020["team"] == df["team"]]["total_games"].values[0] 
        except IndexError: #Handle traded players by returning the average num_games played by all teams
            return int(df_num_games_2020["total_games"].mean())
    elif df["season"] == 2023: 
        try: 
            return df_num_games_2023[df_num_games_2023["team"] == df["team"]]["total_games"].values[0] 
        except IndexError: #Handle traded players by returning the average num_games played by all teams
            return int(df_num_games_2023["total_games"].mean())
    else: 
        return 82

In [15]:
df_per_game["total_games"] = df_per_game.apply(lambda x: fill_total_games(x), axis = 1)
df_per_game["games_played"] = df_per_game["games_played"]/df_per_game["total_games"] 
df_per_game = df_per_game.rename(columns = {"games_played": "%games_played"}).drop("total_games", axis = 1)
df_per_game

,season,slug,name,team,age,%games_played,minutes_played,points,assists,attempted_field_goals,...,blocks,defensive_rebounds,games_started,made_field_goals,made_free_throws,made_three_point_field_goals,offensive_rebounds,personal_fouls,steals,turnovers
0,2010,aldrila01,LaMarcus Aldridge,PORTLAND TRAIL BLAZERS,24,0.951220,37.461538,17.858974,2.051282,14.987179,...,0.615385,5.576923,1.000000,7.423077,2.948718,0.064103,2.461538,2.961538,0.858974,1.333333
1,2010,allenra02,Ray Allen,BOSTON CELTICS,34,0.975610,35.237500,16.300000,2.625000,12.162500,...,0.312500,2.600000,1.000000,5.800000,2.887500,1.812500,0.562500,2.275000,0.800000,1.612500
2,2010,anthoca01,Carmelo Anthony,DENVER NUGGETS,25,0.841463,38.173913,28.159420,3.217391,21.768116,...,0.434783,4.376812,1.000000,9.971014,7.362319,0.855072,2.202899,3.260870,1.275362,3.028986
3,2010,arenagi01,Gilbert Arenas,WASHINGTON WIZARDS,28,0.390244,36.531250,22.562500,7.187500,19.250000,...,0.281250,3.625000,1.000000,7.906250,4.781250,1.968750,0.531250,2.968750,1.281250,3.656250
4,2010,arizatr01,Trevor Ariza,HOUSTON ROCKETS,24,0.878049,36.513889,14.888889,3.833333,13.875000,...,0.555556,4.513889,0.986111,5.472222,2.055556,1.888889,1.083333,2.250000,1.750000,2.236111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1372,2023,washipj01,P.J. Washington,CHARLOTTE HORNETS,24,0.931507,32.867647,15.088235,2.338235,13.000000,...,1.132353,3.867647,1.000000,5.705882,1.691176,1.985294,0.985294,2.676471,0.897059,1.485294
1373,2023,westbru01,Russell Westbrook,LOS ANGELES CLIPPERS,34,0.150685,30.363636,13.090909,7.818182,11.545455,...,0.272727,3.909091,1.000000,5.181818,1.909091,0.818182,1.272727,2.363636,1.272727,3.818182
1374,2023,wiggian01,Andrew Wiggins,GOLDEN STATE WARRIORS,27,0.500000,32.162162,17.108108,2.297297,14.297297,...,0.756757,3.378378,1.000000,6.756757,1.189189,2.405405,1.648649,2.891892,1.216216,1.297297
1375,2023,willizi01,Zion Williamson,NEW ORLEANS PELICANS,22,0.402778,32.965517,26.000000,4.586207,16.172414,...,0.551724,4.965517,1.000000,9.827586,6.103448,0.241379,2.000000,2.241379,1.103448,3.413793
1376,2023,youngtr01,Trae Young,ATLANTA HAWKS,24,0.876712,34.875000,26.734375,10.031250,19.609375,...,0.140625,2.281250,1.000000,8.515625,7.500000,2.203125,0.812500,1.468750,1.125000,4.078125

In [16]:
df_advanced["total_games"] = df_advanced.apply(lambda x: fill_total_games(x), axis = 1)
df_advanced["games_played"] = df_advanced["games_played"]/df_advanced["total_games"] 
df_advanced = df_advanced.rename(columns = {"games_played": "%games_played"}).drop("total_games", axis = 1)
df_advanced

,season,slug,name,team,age,%games_played,assist_percentage,block_percentage,box_plus_minus,defensive_box_plus_minus,...,player_efficiency_rating,steal_percentage,three_point_attempt_rate,total_rebound_percentage,true_shooting_percentage,turnover_percentage,usage_percentage,value_over_replacement_player,win_shares,win_shares_per_48_minutes
0,2012,jamesle01,LeBron James,MIAMI HEAT,27,0.939394,33.6,1.7,10.9,2.7,...,30.7,2.6,0.127,12.6,0.605,13.3,32.0,7.6,14.5,0.298
1,2012,fesenky01,Kyrylo Fesenko,INDIANA PACERS,25,0.045455,9.5,0.0,8.4,3.6,...,29.8,6.2,0.000,29.8,0.524,0.0,20.4,0.0,0.1,0.374
2,2012,paulch01,Chris Paul,LOS ANGELES CLIPPERS,26,0.909091,43.8,0.2,9.2,2.4,...,27.0,3.8,0.239,5.8,0.581,10.8,24.3,6.1,12.7,0.278
3,2012,wadedw01,Dwyane Wade,MIAMI HEAT,30,0.742424,27.3,3.1,7.9,1.9,...,26.3,2.7,0.067,8.7,0.559,11.8,31.3,4.0,7.7,0.227
4,2012,duranke01,Kevin Durant,OKLAHOMA CITY THUNDER,23,1.000000,17.5,2.2,7.0,0.8,...,26.2,1.8,0.265,11.8,0.610,14.0,31.3,5.8,12.2,0.230
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8025,2023,jacksfr01,Frank Jackson,UTAH JAZZ,24,0.013889,22.8,0.0,-22.2,-9.8,...,-6.8,0.0,0.333,21.7,0.000,0.0,25.1,0.0,0.0,-0.374
8026,2023,bouyeja01,Jamaree Bouyea,WASHINGTON WIZARDS,23,0.013699,0.0,0.0,-17.8,-1.7,...,-7.0,0.0,1.000,9.3,0.000,0.0,7.3,0.0,0.0,-0.149
8027,2023,simonma01,Marko Simonovic,CHICAGO BULLS,23,0.041667,0.0,0.0,-21.7,-5.8,...,-10.8,0.0,1.000,0.0,0.000,0.0,8.8,0.0,0.0,-0.201
8028,2023,burtode02,Deonte Burton,SACRAMENTO KINGS,29,0.027778,0.0,0.0,-24.7,-10.0,...,-12.6,0.0,0.500,0.0,0.000,0.0,14.3,0.0,0.0,-0.349
8029,2023,willial06,Alondes Williams,BROOKLYN NETS,23,0.013889,0.0,0.0,-26.6,-5.3,...,-20.9,0.0,0.000,11.3,0.000,100.0,17.8,0.0,-0.1,-0.517

## Create field_goal%, free_throw%, and 3pt%

In [17]:
df_per_game["field_goal%"] = df_per_game["made_field_goals"]/df_per_game["attempted_field_goals"] 
df_per_game["free_throw%"] = df_per_game["made_free_throws"]/df_per_game["attempted_free_throws"] 
df_per_game["3pt"] = df_per_game["made_three_point_field_goals"]/df_per_game["attempted_three_point_field_goals"] 
df_per_game

,season,slug,name,team,age,%games_played,minutes_played,points,assists,attempted_field_goals,...,made_field_goals,made_free_throws,made_three_point_field_goals,offensive_rebounds,personal_fouls,steals,turnovers,field_goal%,free_throw%,3pt
0,2010,aldrila01,LaMarcus Aldridge,PORTLAND TRAIL BLAZERS,24,0.951220,37.461538,17.858974,2.051282,14.987179,...,7.423077,2.948718,0.064103,2.461538,2.961538,0.858974,1.333333,0.495295,0.756579,0.312500
1,2010,allenra02,Ray Allen,BOSTON CELTICS,34,0.975610,35.237500,16.300000,2.625000,12.162500,...,5.800000,2.887500,1.812500,0.562500,2.275000,0.800000,1.612500,0.476876,0.913043,0.363409
2,2010,anthoca01,Carmelo Anthony,DENVER NUGGETS,25,0.841463,38.173913,28.159420,3.217391,21.768116,...,9.971014,7.362319,0.855072,2.202899,3.260870,1.275362,3.028986,0.458056,0.830065,0.315508
3,2010,arenagi01,Gilbert Arenas,WASHINGTON WIZARDS,28,0.390244,36.531250,22.562500,7.187500,19.250000,...,7.906250,4.781250,1.968750,0.531250,2.968750,1.281250,3.656250,0.410714,0.739130,0.348066
4,2010,arizatr01,Trevor Ariza,HOUSTON ROCKETS,24,0.878049,36.513889,14.888889,3.833333,13.875000,...,5.472222,2.055556,1.888889,1.083333,2.250000,1.750000,2.236111,0.394394,0.649123,0.334152
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1372,2023,washipj01,P.J. Washington,CHARLOTTE HORNETS,24,0.931507,32.867647,15.088235,2.338235,13.000000,...,5.705882,1.691176,1.985294,0.985294,2.676471,0.897059,1.485294,0.438914,0.718750,0.347044
1373,2023,westbru01,Russell Westbrook,LOS ANGELES CLIPPERS,34,0.150685,30.363636,13.090909,7.818182,11.545455,...,5.181818,1.909091,0.818182,1.272727,2.363636,1.272727,3.818182,0.448819,0.700000,0.272727
1374,2023,wiggian01,Andrew Wiggins,GOLDEN STATE WARRIORS,27,0.500000,32.162162,17.108108,2.297297,14.297297,...,6.756757,1.189189,2.405405,1.648649,2.891892,1.216216,1.297297,0.472590,0.611111,0.395556
1375,2023,willizi01,Zion Williamson,NEW ORLEANS PELICANS,22,0.402778,32.965517,26.000000,4.586207,16.172414,...,9.827586,6.103448,0.241379,2.000000,2.241379,1.103448,3.413793,0.607676,0.713710,0.368421
1376,2023,youngtr01,Trae Young,ATLANTA HAWKS,24,0.876712,34.875000,26.734375,10.031250,19.609375,...,8.515625,7.500000,2.203125,0.812500,1.468750,1.125000,4.078125,0.434263,0.887246,0.337321

## Eliminate Counting Stats

In [18]:
counting_stats = ["win_shares", "offensive_win_shares", "defensive_win_shares"]
df_advanced.drop(columns = counting_stats, axis = 1, inplace = True) 
df_advanced

,season,slug,name,team,age,%games_played,assist_percentage,block_percentage,box_plus_minus,defensive_box_plus_minus,...,offensive_rebound_percentage,player_efficiency_rating,steal_percentage,three_point_attempt_rate,total_rebound_percentage,true_shooting_percentage,turnover_percentage,usage_percentage,value_over_replacement_player,win_shares_per_48_minutes
0,2012,jamesle01,LeBron James,MIAMI HEAT,27,0.939394,33.6,1.7,10.9,2.7,...,5.0,30.7,2.6,0.127,12.6,0.605,13.3,32.0,7.6,0.298
1,2012,fesenky01,Kyrylo Fesenko,INDIANA PACERS,25,0.045455,9.5,0.0,8.4,3.6,...,13.3,29.8,6.2,0.000,29.8,0.524,0.0,20.4,0.0,0.374
2,2012,paulch01,Chris Paul,LOS ANGELES CLIPPERS,26,0.909091,43.8,0.2,9.2,2.4,...,2.3,27.0,3.8,0.239,5.8,0.581,10.8,24.3,6.1,0.278
3,2012,wadedw01,Dwyane Wade,MIAMI HEAT,30,0.742424,27.3,3.1,7.9,1.9,...,5.6,26.3,2.7,0.067,8.7,0.559,11.8,31.3,4.0,0.227
4,2012,duranke01,Kevin Durant,OKLAHOMA CITY THUNDER,23,1.000000,17.5,2.2,7.0,0.8,...,1.9,26.2,1.8,0.265,11.8,0.610,14.0,31.3,5.8,0.230
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8025,2023,jacksfr01,Frank Jackson,UTAH JAZZ,24,0.013889,22.8,0.0,-22.2,-9.8,...,22.0,-6.8,0.0,0.333,21.7,0.000,0.0,25.1,0.0,-0.374
8026,2023,bouyeja01,Jamaree Bouyea,WASHINGTON WIZARDS,23,0.013699,0.0,0.0,-17.8,-1.7,...,0.0,-7.0,0.0,1.000,9.3,0.000,0.0,7.3,0.0,-0.149
8027,2023,simonma01,Marko Simonovic,CHICAGO BULLS,23,0.041667,0.0,0.0,-21.7,-5.8,...,0.0,-10.8,0.0,1.000,0.0,0.000,0.0,8.8,0.0,-0.201
8028,2023,burtode02,Deonte Burton,SACRAMENTO KINGS,29,0.027778,0.0,0.0,-24.7,-10.0,...,0.0,-12.6,0.0,0.500,0.0,0.000,0.0,14.3,0.0,-0.349
8029,2023,willial06,Alondes Williams,BROOKLYN NETS,23,0.013889,0.0,0.0,-26.6,-5.3,...,0.0,-20.9,0.0,0.000,11.3,0.000,100.0,17.8,0.0,-0.517

# Merge box score and advanced stats to create `df_players`

In [19]:
df_players = df_per_game.merge(df_advanced, how = "inner", on = ["season", "slug", "name", "team", "age", "%games_played"])
df_players

,season,slug,name,team,age,%games_played,minutes_played,points,assists,attempted_field_goals,...,offensive_rebound_percentage,player_efficiency_rating,steal_percentage,three_point_attempt_rate,total_rebound_percentage,true_shooting_percentage,turnover_percentage,usage_percentage,value_over_replacement_player,win_shares_per_48_minutes
0,2010,aldrila01,LaMarcus Aldridge,PORTLAND TRAIL BLAZERS,24,0.951220,37.461538,17.858974,2.051282,14.987179,...,8.1,18.2,1.3,0.014,13.3,0.535,7.4,22.9,2.3,0.145
1,2010,allenra02,Ray Allen,BOSTON CELTICS,34,0.975610,35.237500,16.300000,2.625000,12.162500,...,2.0,15.2,1.2,0.410,5.5,0.601,10.6,20.2,2.3,0.135
2,2010,anthoca01,Carmelo Anthony,DENVER NUGGETS,25,0.841463,38.173913,28.159420,3.217391,21.768116,...,6.7,22.2,1.7,0.125,9.9,0.548,10.6,33.4,2.9,0.145
3,2010,arenagi01,Gilbert Arenas,WASHINGTON WIZARDS,28,0.390244,36.531250,22.562500,7.187500,19.250000,...,1.6,18.7,1.8,0.294,6.5,0.511,14.2,31.9,1.1,0.072
4,2010,arizatr01,Trevor Ariza,HOUSTON ROCKETS,24,0.878049,36.513889,14.888889,3.833333,13.875000,...,3.3,13.3,2.4,0.407,8.8,0.488,12.8,21.2,1.7,0.058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1316,2023,washipj01,P.J. Washington,CHARLOTTE HORNETS,24,0.931507,32.867647,15.088235,2.338235,13.000000,...,3.1,12.4,1.3,0.440,7.8,0.538,9.6,19.8,0.2,0.048
1317,2023,westbru01,Russell Westbrook,LOS ANGELES CLIPPERS,34,0.150685,30.363636,13.090909,7.818182,11.545455,...,4.7,14.0,2.1,0.260,9.5,0.514,23.1,23.8,0.0,0.033
1318,2023,wiggian01,Andrew Wiggins,GOLDEN STATE WARRIORS,27,0.500000,32.162162,17.108108,2.297297,14.297297,...,5.7,14.8,1.8,0.425,8.6,0.564,7.9,21.5,0.4,0.087
1319,2023,willizi01,Zion Williamson,NEW ORLEANS PELICANS,22,0.402778,32.965517,26.000000,4.586207,16.172414,...,6.8,25.3,1.6,0.041,11.9,0.652,14.6,30.3,1.8,0.175
1320,2023,youngtr01,Trae Young,ATLANTA HAWKS,24,0.876712,34.875000,26.734375,10.031250,19.609375,...,2.5,22.5,1.5,0.333,4.8,0.573,14.9,33.1,3.2,0.128

In [25]:
df_players.columns

Index(['season', 'slug', 'name', 'team', 'age', '%games_played',
       'minutes_played', 'points', 'assists', 'attempted_field_goals',
       'attempted_free_throws', 'attempted_three_point_field_goals', 'blocks',
       'defensive_rebounds', 'games_started', 'made_field_goals',
       'made_free_throws', 'made_three_point_field_goals',
       'offensive_rebounds', 'personal_fouls', 'steals', 'turnovers',
       'field_goal%', 'free_throw%', '3pt', 'assist_percentage',
       'block_percentage', 'box_plus_minus', 'defensive_box_plus_minus',
       'defensive_rebound_percentage', 'free_throw_attempt_rate',
       'offensive_box_plus_minus', 'offensive_rebound_percentage',
       'player_efficiency_rating', 'steal_percentage',
       'three_point_attempt_rate', 'total_rebound_percentage',
       'true_shooting_percentage', 'turnover_percentage', 'usage_percentage',
       'value_over_replacement_player', 'win_shares_per_48_minutes', 'is_mvp'],
      dtype='object')

## Separate 2023 data from the rest (2010 – 2022)

In [20]:
df_players_2023 = df_players[df_players["season"] == 2023] 
df_players = df_players[df_players["season"] != 2023]

## Add label for MVP winners

In [21]:
df_mvp = pd.read_csv("../Data/mvp_winners_history.csv") 
df_mvp = df_mvp.iloc[1:, [0, 2, -1]] 
df_mvp.rename(columns = {"Unnamed: 0": "season", "Unnamed: 2": "name", "-additional": "slug"}, inplace = True) 
df_mvp["season"] = df_mvp["season"].apply(lambda x: int(x[:-3]) + 1)
df_mvp

    season                   name       slug
1     2022           Nikola Jokić  jokicni01
2     2021           Nikola Jokić  jokicni01
3     2020  Giannis Antetokounmpo  antetgi01
4     2019  Giannis Antetokounmpo  antetgi01
5     2018           James Harden  hardeja01
6     2017      Russell Westbrook  westbru01
7     2016          Stephen Curry  curryst01
8     2015          Stephen Curry  curryst01
9     2014           Kevin Durant  duranke01
10    2013           LeBron James  jamesle01
11    2012           LeBron James  jamesle01
12    2011           Derrick Rose   rosede01
13    2010           LeBron James  jamesle01

In [22]:
def label_mvp(df): 
    if (df["slug"] == df_mvp[df_mvp["season"] == df["season"]]["slug"].values[0]): 
        return 1 
    else: 
        return 0

In [23]:
df_players["is_mvp"] = df_players.apply(lambda x: label_mvp(x), axis = 1) 
df_players

/var/folders/64/lts2my7j2q3g96y6cn7715xw0000gn/T/ipykernel_39595/2410801324.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_players["is_mvp"] = df_players.apply(lambda x: label_mvp(x), axis = 1)

,season,slug,name,team,age,%games_played,minutes_played,points,assists,attempted_field_goals,...,player_efficiency_rating,steal_percentage,three_point_attempt_rate,total_rebound_percentage,true_shooting_percentage,turnover_percentage,usage_percentage,value_over_replacement_player,win_shares_per_48_minutes,is_mvp
0,2010,aldrila01,LaMarcus Aldridge,PORTLAND TRAIL BLAZERS,24,0.951220,37.461538,17.858974,2.051282,14.987179,...,18.2,1.3,0.014,13.3,0.535,7.4,22.9,2.3,0.145,0
1,2010,allenra02,Ray Allen,BOSTON CELTICS,34,0.975610,35.237500,16.300000,2.625000,12.162500,...,15.2,1.2,0.410,5.5,0.601,10.6,20.2,2.3,0.135,0
2,2010,anthoca01,Carmelo Anthony,DENVER NUGGETS,25,0.841463,38.173913,28.159420,3.217391,21.768116,...,22.2,1.7,0.125,9.9,0.548,10.6,33.4,2.9,0.145,0
3,2010,arenagi01,Gilbert Arenas,WASHINGTON WIZARDS,28,0.390244,36.531250,22.562500,7.187500,19.250000,...,18.7,1.8,0.294,6.5,0.511,14.2,31.9,1.1,0.072,0
4,2010,arizatr01,Trevor Ariza,HOUSTON ROCKETS,24,0.878049,36.513889,14.888889,3.833333,13.875000,...,13.3,2.4,0.407,8.8,0.488,12.8,21.2,1.7,0.058,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1211,2022,westbru01,Russell Westbrook,LOS ANGELES LAKERS,33,0.951220,34.333333,18.474359,7.051282,15.807692,...,15.0,1.3,0.215,11.6,0.512,17.3,27.3,0.2,0.030,0
1212,2022,whitede01,Derrick White,SAN ANTONIO SPURS,27,0.597561,30.326531,14.408163,5.591837,11.632653,...,15.7,1.6,0.453,6.1,0.551,12.0,20.7,1.4,0.107,0
1213,2022,wiggian01,Andrew Wiggins,GOLDEN STATE WARRIORS,26,0.890244,31.904110,17.205479,2.205479,13.958904,...,15.0,1.6,0.392,7.6,0.560,9.0,23.1,1.4,0.105,0
1214,2022,woodch01,Christian Wood,HOUSTON ROCKETS,26,0.829268,30.794118,17.911765,2.279412,12.911765,...,19.1,1.2,0.383,18.0,0.595,11.0,23.3,1.9,0.112,0
1215,2022,youngtr01,Trae Young,ATLANTA HAWKS,23,0.926829,34.894737,28.355263,9.697368,20.315789,...,25.4,1.3,0.395,5.9,0.603,14.5,34.4,4.8,0.181,0

# Exporting data

In [24]:
df_players.to_csv("../Data/player_data.csv")
df_players_2023.to_csv("../Data/player_data_2023.csv")