In [93]:
import pandas as pd

# Import Data

## Import Player Data

### Past Player Data

In [94]:
df_players = pd.read_csv("../Data/player_data.csv")
df_players.drop("Unnamed: 0", axis = 1, inplace = True) 
df_players

,season,slug,name,team,age,%games_played,minutes_played,points,assists,attempted_field_goals,...,player_efficiency_rating,steal_percentage,three_point_attempt_rate,total_rebound_percentage,true_shooting_percentage,turnover_percentage,usage_percentage,value_over_replacement_player,win_shares_per_48_minutes,is_mvp
0,2010,aldrila01,LaMarcus Aldridge,PORTLAND TRAIL BLAZERS,24,0.951220,37.461538,17.858974,2.051282,14.987179,...,18.2,1.3,0.014,13.3,0.535,7.4,22.9,2.3,0.145,0
1,2010,allenra02,Ray Allen,BOSTON CELTICS,34,0.975610,35.237500,16.300000,2.625000,12.162500,...,15.2,1.2,0.410,5.5,0.601,10.6,20.2,2.3,0.135,0
2,2010,anthoca01,Carmelo Anthony,DENVER NUGGETS,25,0.841463,38.173913,28.159420,3.217391,21.768116,...,22.2,1.7,0.125,9.9,0.548,10.6,33.4,2.9,0.145,0
3,2010,arenagi01,Gilbert Arenas,WASHINGTON WIZARDS,28,0.390244,36.531250,22.562500,7.187500,19.250000,...,18.7,1.8,0.294,6.5,0.511,14.2,31.9,1.1,0.072,0
4,2010,arizatr01,Trevor Ariza,HOUSTON ROCKETS,24,0.878049,36.513889,14.888889,3.833333,13.875000,...,13.3,2.4,0.407,8.8,0.488,12.8,21.2,1.7,0.058,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1211,2022,westbru01,Russell Westbrook,LOS ANGELES LAKERS,33,0.951220,34.333333,18.474359,7.051282,15.807692,...,15.0,1.3,0.215,11.6,0.512,17.3,27.3,0.2,0.030,0
1212,2022,whitede01,Derrick White,SAN ANTONIO SPURS,27,0.597561,30.326531,14.408163,5.591837,11.632653,...,15.7,1.6,0.453,6.1,0.551,12.0,20.7,1.4,0.107,0
1213,2022,wiggian01,Andrew Wiggins,GOLDEN STATE WARRIORS,26,0.890244,31.904110,17.205479,2.205479,13.958904,...,15.0,1.6,0.392,7.6,0.560,9.0,23.1,1.4,0.105,0
1214,2022,woodch01,Christian Wood,HOUSTON ROCKETS,26,0.829268,30.794118,17.911765,2.279412,12.911765,...,19.1,1.2,0.383,18.0,0.595,11.0,23.3,1.9,0.112,0
1215,2022,youngtr01,Trae Young,ATLANTA HAWKS,23,0.926829,34.894737,28.355263,9.697368,20.315789,...,25.4,1.3,0.395,5.9,0.603,14.5,34.4,4.8,0.181,0

In [95]:
df_label = df_players[["season", "name", "is_mvp"]]
df_players.drop("is_mvp", axis=1, inplace=True)
df_label

      season               name  is_mvp
0       2010  LaMarcus Aldridge       0
1       2010          Ray Allen       0
2       2010    Carmelo Anthony       0
3       2010     Gilbert Arenas       0
4       2010       Trevor Ariza       0
...      ...                ...     ...
1211    2022  Russell Westbrook       0
1212    2022      Derrick White       0
1213    2022     Andrew Wiggins       0
1214    2022     Christian Wood       0
1215    2022         Trae Young       0

[1216 rows x 3 columns]

### 2023 Player Data

In [103]:
df_players_2023 = pd.read_csv("../Data/player_data_2023.csv")
df_players_2023.drop("Unnamed: 0", axis = 1, inplace = True) 
df_players_2023

,season,slug,name,team,age,%games_played,minutes_played,points,assists,attempted_field_goals,...,offensive_rebound_percentage,player_efficiency_rating,steal_percentage,three_point_attempt_rate,total_rebound_percentage,true_shooting_percentage,turnover_percentage,usage_percentage,value_over_replacement_player,win_shares_per_48_minutes
0,2023,adebaba01,Bam Adebayo,MIAMI HEAT,25,0.918919,35.132353,21.058824,3.279412,15.250000,...,7.8,20.4,1.7,0.012,15.5,0.595,12.8,25.5,2.3,0.142
1,2023,allenja01,Jarrett Allen,CLEVELAND CAVALIERS,24,0.837838,33.032258,14.354839,1.677419,9.225806,...,11.1,19.8,1.3,0.016,17.5,0.673,11.6,16.3,2.2,0.204
2,2023,antetgi01,Giannis Antetokounmpo,MILWAUKEE BUCKS,28,0.777778,32.500000,31.250000,5.571429,20.392857,...,7.5,28.6,1.1,0.137,18.9,0.602,13.1,38.7,4.7,0.204
3,2023,anunoog01,OG Anunoby,TORONTO RAPTORS,25,0.794521,35.724138,16.775862,1.896552,13.103448,...,4.2,14.4,2.7,0.401,8.0,0.586,13.1,19.6,1.1,0.085
4,2023,aytonde01,Deandre Ayton,PHOENIX SUNS,24,0.847222,30.442623,18.311475,1.819672,13.557377,...,9.5,20.3,0.9,0.029,18.5,0.616,10.9,23.4,1.5,0.150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,2023,washipj01,P.J. Washington,CHARLOTTE HORNETS,24,0.931507,32.867647,15.088235,2.338235,13.000000,...,3.1,12.4,1.3,0.440,7.8,0.538,9.6,19.8,0.2,0.048
101,2023,westbru01,Russell Westbrook,LOS ANGELES CLIPPERS,34,0.150685,30.363636,13.090909,7.818182,11.545455,...,4.7,14.0,2.1,0.260,9.5,0.514,23.1,23.8,0.0,0.033
102,2023,wiggian01,Andrew Wiggins,GOLDEN STATE WARRIORS,27,0.500000,32.162162,17.108108,2.297297,14.297297,...,5.7,14.8,1.8,0.425,8.6,0.564,7.9,21.5,0.4,0.087
103,2023,willizi01,Zion Williamson,NEW ORLEANS PELICANS,22,0.402778,32.965517,26.000000,4.586207,16.172414,...,6.8,25.3,1.6,0.041,11.9,0.652,14.6,30.3,1.8,0.175
104,2023,youngtr01,Trae Young,ATLANTA HAWKS,24,0.876712,34.875000,26.734375,10.031250,19.609375,...,2.5,22.5,1.5,0.333,4.8,0.573,14.9,33.1,3.2,0.128

## Import Team Data

### Past Team Data

In [96]:
df_teams = pd.read_csv("../Data/team_data.csv")
df_teams.drop("Unnamed: 0", axis=1, inplace=True) 
df_teams

,season,team,conference,W,L,win_rate,conference_standing
0,2022,PHOENIX SUNS,Western,64,18,0.780488,1
1,2022,MEMPHIS GRIZZLIES,Western,56,26,0.682927,2
2,2022,GOLDEN STATE WARRIORS,Western,53,29,0.646341,3
3,2022,DALLAS MAVERICKS,Western,52,30,0.634146,4
4,2022,UTAH JAZZ,Western,49,33,0.597561,5
...,...,...,...,...,...,...,...
385,2010,NEW YORK KNICKS,Eastern,29,53,0.353659,11
386,2010,PHILADELPHIA 76ERS,Eastern,27,55,0.329268,12
387,2010,DETROIT PISTONS,Eastern,27,55,0.329268,13
388,2010,WASHINGTON WIZARDS,Eastern,26,56,0.317073,14
389,2010,NEW JERSEY NETS,Eastern,12,70,0.146341,15

### 2023 Team Data

In [104]:
df_teams_2023 = pd.read_csv("../Data/team_data_2023.csv")
df_teams_2023.drop("Unnamed: 0", axis=1, inplace=True) 
df_teams_2023

,season,team,conference,W,L,win_rate,conference_standing
0,2023,DENVER NUGGETS,Western,48,24,0.666667,1
1,2023,MEMPHIS GRIZZLIES,Western,43,27,0.614286,2
2,2023,SACRAMENTO KINGS,Western,43,27,0.614286,3
3,2023,PHOENIX SUNS,Western,38,33,0.535211,4
4,2023,LOS ANGELES CLIPPERS,Western,38,34,0.527778,5
5,2023,DALLAS MAVERICKS,Western,36,35,0.507042,6
6,2023,GOLDEN STATE WARRIORS,Western,36,36,0.500000,7
7,2023,OKLAHOMA CITY THUNDER,Western,35,36,0.492958,8
8,2023,MINNESOTA TIMBERWOLVES,Western,35,37,0.486111,9
9,2023,LOS ANGELES LAKERS,Western,35,37,0.486111,10
10,2023,UTAH JAZZ,Western,34,36,0.485714,11
11,2023,NEW ORLEANS PELICANS,Western,34,37,0.478873,12
12,2023,PORTLAND TRAIL BLAZERS,Western,31,40,0.436620,13
13,2023,SAN ANTONIO SPURS,Western,19,52,0.267606,14
14,2023,HOUSTON ROCKETS,Western,18,53,0.253521,15
15,2023,MILWAUKEE BUCKS,Eastern,51,20,0.718310,1
16,2023,PHILADELPHIA 76ERS,Eastern,48,22,0.685714,2
17,2023,BOSTON CELTICS,Eastern,49,23,0.680556,3
18,2023,CLEVELAND CAVALIERS,Eastern,45,28,0.616438,4
19,2023,NEW YORK KNICKS,Eastern,42,30,0.583333,5
20,2023,BROOKLYN NETS,Eastern,39,32,0.549296,6
21,2023,MIAMI HEAT,Eastern,39,34,0.534247,7
22,2023,ATLANTA HAWKS,Eastern,35,36,0.492958,8
23,2023,TORONTO RAPTORS,Eastern,35,37,0.486111,9
24,2023,CHICAGO BULLS,Eastern,33,37,0.471429,10
25,2023,INDIANA PACERS,Eastern,32,39,0.450704,11
26,2023,WASHINGTON WIZARDS,Eastern,32,39,0.450704,12
27,2023,ORLANDO MAGIC,Eastern,29,43,0.402778,13
28,2023,CHARLOTTE HORNETS,Eastern,22,50,0.305556,14
29,2023,DETROIT PISTONS,Eastern,16,56,0.222222,15

## Import Media Narrative Data

`MVP_count.csv` is designed to capture the number of time a player have won MVP and whether he has won it the previous year or previous 2 years. It is generally agreed upon that players who win their first MVP the previous year tend to win another MVP, whilst players who have won MVP 2 years in a row are highly unlikely to win a third one (sometimes termed "voter fatigue"). This dataset is designed to capture the aspect of "voter fatigue".

In [97]:
df_mvp_count = pd.read_csv("../Data/MVP_count.csv")
df_mvp_count.rename(columns={"Name":"name", "Year":"season", "value":"num_mvp"}, inplace=True) 
df_mvp_count

             name  season  num_mvp  won_last_yr  won_2_yrs_before
0     Joel Embiid    2023        0            0                 0
1     Joel Embiid    2022        0            0                 0
2     Joel Embiid    2021        0            0                 0
3     Joel Embiid    2020        0            0                 0
4     Joel Embiid    2019        0            0                 0
...           ...     ...      ...          ...               ...
2407    Bob Cousy    1961        1            0                 0
2408    Bob Cousy    1960        1            0                 0
2409    Bob Cousy    1959        1            0                 1
2410    Bob Cousy    1958        1            1                 0
2411    Bob Cousy    1957        0            0                 0

[2412 rows x 5 columns]

# Merge Data

## Merge Past Data

In [98]:
df_final = pd.merge(df_players, df_teams, on=["season", "team"], how="left") 
df_final.drop(["conference", "W", "L"], axis=1, inplace=True)
df_final

,season,slug,name,team,age,%games_played,minutes_played,points,assists,attempted_field_goals,...,steal_percentage,three_point_attempt_rate,total_rebound_percentage,true_shooting_percentage,turnover_percentage,usage_percentage,value_over_replacement_player,win_shares_per_48_minutes,win_rate,conference_standing
0,2010,aldrila01,LaMarcus Aldridge,PORTLAND TRAIL BLAZERS,24,0.951220,37.461538,17.858974,2.051282,14.987179,...,1.3,0.014,13.3,0.535,7.4,22.9,2.3,0.145,0.609756,6
1,2010,allenra02,Ray Allen,BOSTON CELTICS,34,0.975610,35.237500,16.300000,2.625000,12.162500,...,1.2,0.410,5.5,0.601,10.6,20.2,2.3,0.135,0.609756,4
2,2010,anthoca01,Carmelo Anthony,DENVER NUGGETS,25,0.841463,38.173913,28.159420,3.217391,21.768116,...,1.7,0.125,9.9,0.548,10.6,33.4,2.9,0.145,0.646341,4
3,2010,arenagi01,Gilbert Arenas,WASHINGTON WIZARDS,28,0.390244,36.531250,22.562500,7.187500,19.250000,...,1.8,0.294,6.5,0.511,14.2,31.9,1.1,0.072,0.317073,14
4,2010,arizatr01,Trevor Ariza,HOUSTON ROCKETS,24,0.878049,36.513889,14.888889,3.833333,13.875000,...,2.4,0.407,8.8,0.488,12.8,21.2,1.7,0.058,0.512195,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1211,2022,westbru01,Russell Westbrook,LOS ANGELES LAKERS,33,0.951220,34.333333,18.474359,7.051282,15.807692,...,1.3,0.215,11.6,0.512,17.3,27.3,0.2,0.030,0.402439,11
1212,2022,whitede01,Derrick White,SAN ANTONIO SPURS,27,0.597561,30.326531,14.408163,5.591837,11.632653,...,1.6,0.453,6.1,0.551,12.0,20.7,1.4,0.107,0.414634,10
1213,2022,wiggian01,Andrew Wiggins,GOLDEN STATE WARRIORS,26,0.890244,31.904110,17.205479,2.205479,13.958904,...,1.6,0.392,7.6,0.560,9.0,23.1,1.4,0.105,0.646341,3
1214,2022,woodch01,Christian Wood,HOUSTON ROCKETS,26,0.829268,30.794118,17.911765,2.279412,12.911765,...,1.2,0.383,18.0,0.595,11.0,23.3,1.9,0.112,0.243902,15
1215,2022,youngtr01,Trae Young,ATLANTA HAWKS,23,0.926829,34.894737,28.355263,9.697368,20.315789,...,1.3,0.395,5.9,0.603,14.5,34.4,4.8,0.181,0.524390,9

In [99]:
df_final = pd.merge(df_final, df_mvp_count, on=["season", "name"], how="left") 
df_final = df_final.fillna(0)
df_final[["num_mvp", "won_last_yr", "won_2_yrs_before"]] = df_final[["num_mvp", "won_last_yr", "won_2_yrs_before"]].astype(int)
df_final

,season,slug,name,team,age,%games_played,minutes_played,points,assists,attempted_field_goals,...,true_shooting_percentage,turnover_percentage,usage_percentage,value_over_replacement_player,win_shares_per_48_minutes,win_rate,conference_standing,num_mvp,won_last_yr,won_2_yrs_before
0,2010,aldrila01,LaMarcus Aldridge,PORTLAND TRAIL BLAZERS,24,0.951220,37.461538,17.858974,2.051282,14.987179,...,0.535,7.4,22.9,2.3,0.145,0.609756,6,0,0,0
1,2010,allenra02,Ray Allen,BOSTON CELTICS,34,0.975610,35.237500,16.300000,2.625000,12.162500,...,0.601,10.6,20.2,2.3,0.135,0.609756,4,0,0,0
2,2010,anthoca01,Carmelo Anthony,DENVER NUGGETS,25,0.841463,38.173913,28.159420,3.217391,21.768116,...,0.548,10.6,33.4,2.9,0.145,0.646341,4,0,0,0
3,2010,arenagi01,Gilbert Arenas,WASHINGTON WIZARDS,28,0.390244,36.531250,22.562500,7.187500,19.250000,...,0.511,14.2,31.9,1.1,0.072,0.317073,14,0,0,0
4,2010,arizatr01,Trevor Ariza,HOUSTON ROCKETS,24,0.878049,36.513889,14.888889,3.833333,13.875000,...,0.488,12.8,21.2,1.7,0.058,0.512195,9,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1211,2022,westbru01,Russell Westbrook,LOS ANGELES LAKERS,33,0.951220,34.333333,18.474359,7.051282,15.807692,...,0.512,17.3,27.3,0.2,0.030,0.402439,11,1,0,0
1212,2022,whitede01,Derrick White,SAN ANTONIO SPURS,27,0.597561,30.326531,14.408163,5.591837,11.632653,...,0.551,12.0,20.7,1.4,0.107,0.414634,10,0,0,0
1213,2022,wiggian01,Andrew Wiggins,GOLDEN STATE WARRIORS,26,0.890244,31.904110,17.205479,2.205479,13.958904,...,0.560,9.0,23.1,1.4,0.105,0.646341,3,0,0,0
1214,2022,woodch01,Christian Wood,HOUSTON ROCKETS,26,0.829268,30.794118,17.911765,2.279412,12.911765,...,0.595,11.0,23.3,1.9,0.112,0.243902,15,0,0,0
1215,2022,youngtr01,Trae Young,ATLANTA HAWKS,23,0.926829,34.894737,28.355263,9.697368,20.315789,...,0.603,14.5,34.4,4.8,0.181,0.524390,9,0,0,0

## Merge 2023 Data

In [105]:
df_final_2023 = pd.merge(df_players_2023, df_teams_2023, on=["season", "team"], how="left") 
df_final_2023.drop(["conference", "W", "L"], axis=1, inplace=True)
df_final_2023

,season,slug,name,team,age,%games_played,minutes_played,points,assists,attempted_field_goals,...,steal_percentage,three_point_attempt_rate,total_rebound_percentage,true_shooting_percentage,turnover_percentage,usage_percentage,value_over_replacement_player,win_shares_per_48_minutes,win_rate,conference_standing
0,2023,adebaba01,Bam Adebayo,MIAMI HEAT,25,0.918919,35.132353,21.058824,3.279412,15.250000,...,1.7,0.012,15.5,0.595,12.8,25.5,2.3,0.142,0.534247,7
1,2023,allenja01,Jarrett Allen,CLEVELAND CAVALIERS,24,0.837838,33.032258,14.354839,1.677419,9.225806,...,1.3,0.016,17.5,0.673,11.6,16.3,2.2,0.204,0.616438,4
2,2023,antetgi01,Giannis Antetokounmpo,MILWAUKEE BUCKS,28,0.777778,32.500000,31.250000,5.571429,20.392857,...,1.1,0.137,18.9,0.602,13.1,38.7,4.7,0.204,0.718310,1
3,2023,anunoog01,OG Anunoby,TORONTO RAPTORS,25,0.794521,35.724138,16.775862,1.896552,13.103448,...,2.7,0.401,8.0,0.586,13.1,19.6,1.1,0.085,0.486111,9
4,2023,aytonde01,Deandre Ayton,PHOENIX SUNS,24,0.847222,30.442623,18.311475,1.819672,13.557377,...,0.9,0.029,18.5,0.616,10.9,23.4,1.5,0.150,0.535211,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,2023,washipj01,P.J. Washington,CHARLOTTE HORNETS,24,0.931507,32.867647,15.088235,2.338235,13.000000,...,1.3,0.440,7.8,0.538,9.6,19.8,0.2,0.048,0.305556,14
101,2023,westbru01,Russell Westbrook,LOS ANGELES CLIPPERS,34,0.150685,30.363636,13.090909,7.818182,11.545455,...,2.1,0.260,9.5,0.514,23.1,23.8,0.0,0.033,0.527778,5
102,2023,wiggian01,Andrew Wiggins,GOLDEN STATE WARRIORS,27,0.500000,32.162162,17.108108,2.297297,14.297297,...,1.8,0.425,8.6,0.564,7.9,21.5,0.4,0.087,0.500000,7
103,2023,willizi01,Zion Williamson,NEW ORLEANS PELICANS,22,0.402778,32.965517,26.000000,4.586207,16.172414,...,1.6,0.041,11.9,0.652,14.6,30.3,1.8,0.175,0.478873,12
104,2023,youngtr01,Trae Young,ATLANTA HAWKS,24,0.876712,34.875000,26.734375,10.031250,19.609375,...,1.5,0.333,4.8,0.573,14.9,33.1,3.2,0.128,0.492958,8

# Add label

In [100]:
df_final = pd.merge(df_final, df_label, on=["season", "name"], how="left")
df_final

,season,slug,name,team,age,%games_played,minutes_played,points,assists,attempted_field_goals,...,turnover_percentage,usage_percentage,value_over_replacement_player,win_shares_per_48_minutes,win_rate,conference_standing,num_mvp,won_last_yr,won_2_yrs_before,is_mvp
0,2010,aldrila01,LaMarcus Aldridge,PORTLAND TRAIL BLAZERS,24,0.951220,37.461538,17.858974,2.051282,14.987179,...,7.4,22.9,2.3,0.145,0.609756,6,0,0,0,0
1,2010,allenra02,Ray Allen,BOSTON CELTICS,34,0.975610,35.237500,16.300000,2.625000,12.162500,...,10.6,20.2,2.3,0.135,0.609756,4,0,0,0,0
2,2010,anthoca01,Carmelo Anthony,DENVER NUGGETS,25,0.841463,38.173913,28.159420,3.217391,21.768116,...,10.6,33.4,2.9,0.145,0.646341,4,0,0,0,0
3,2010,arenagi01,Gilbert Arenas,WASHINGTON WIZARDS,28,0.390244,36.531250,22.562500,7.187500,19.250000,...,14.2,31.9,1.1,0.072,0.317073,14,0,0,0,0
4,2010,arizatr01,Trevor Ariza,HOUSTON ROCKETS,24,0.878049,36.513889,14.888889,3.833333,13.875000,...,12.8,21.2,1.7,0.058,0.512195,9,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1211,2022,westbru01,Russell Westbrook,LOS ANGELES LAKERS,33,0.951220,34.333333,18.474359,7.051282,15.807692,...,17.3,27.3,0.2,0.030,0.402439,11,1,0,0,0
1212,2022,whitede01,Derrick White,SAN ANTONIO SPURS,27,0.597561,30.326531,14.408163,5.591837,11.632653,...,12.0,20.7,1.4,0.107,0.414634,10,0,0,0,0
1213,2022,wiggian01,Andrew Wiggins,GOLDEN STATE WARRIORS,26,0.890244,31.904110,17.205479,2.205479,13.958904,...,9.0,23.1,1.4,0.105,0.646341,3,0,0,0,0
1214,2022,woodch01,Christian Wood,HOUSTON ROCKETS,26,0.829268,30.794118,17.911765,2.279412,12.911765,...,11.0,23.3,1.9,0.112,0.243902,15,0,0,0,0
1215,2022,youngtr01,Trae Young,ATLANTA HAWKS,23,0.926829,34.894737,28.355263,9.697368,20.315789,...,14.5,34.4,4.8,0.181,0.524390,9,0,0,0,0

In [106]:
df_final_2023 = pd.merge(df_final_2023, df_mvp_count, on=["season", "name"], how="left") 
df_final_2023 = df_final_2023.fillna(0)
df_final_2023[["num_mvp", "won_last_yr", "won_2_yrs_before"]] = df_final_2023[["num_mvp", "won_last_yr", "won_2_yrs_before"]].astype(int)
df_final_2023

,season,slug,name,team,age,%games_played,minutes_played,points,assists,attempted_field_goals,...,true_shooting_percentage,turnover_percentage,usage_percentage,value_over_replacement_player,win_shares_per_48_minutes,win_rate,conference_standing,num_mvp,won_last_yr,won_2_yrs_before
0,2023,adebaba01,Bam Adebayo,MIAMI HEAT,25,0.918919,35.132353,21.058824,3.279412,15.250000,...,0.595,12.8,25.5,2.3,0.142,0.534247,7,0,0,0
1,2023,allenja01,Jarrett Allen,CLEVELAND CAVALIERS,24,0.837838,33.032258,14.354839,1.677419,9.225806,...,0.673,11.6,16.3,2.2,0.204,0.616438,4,0,0,0
2,2023,antetgi01,Giannis Antetokounmpo,MILWAUKEE BUCKS,28,0.777778,32.500000,31.250000,5.571429,20.392857,...,0.602,13.1,38.7,4.7,0.204,0.718310,1,2,0,0
3,2023,anunoog01,OG Anunoby,TORONTO RAPTORS,25,0.794521,35.724138,16.775862,1.896552,13.103448,...,0.586,13.1,19.6,1.1,0.085,0.486111,9,0,0,0
4,2023,aytonde01,Deandre Ayton,PHOENIX SUNS,24,0.847222,30.442623,18.311475,1.819672,13.557377,...,0.616,10.9,23.4,1.5,0.150,0.535211,4,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,2023,washipj01,P.J. Washington,CHARLOTTE HORNETS,24,0.931507,32.867647,15.088235,2.338235,13.000000,...,0.538,9.6,19.8,0.2,0.048,0.305556,14,0,0,0
101,2023,westbru01,Russell Westbrook,LOS ANGELES CLIPPERS,34,0.150685,30.363636,13.090909,7.818182,11.545455,...,0.514,23.1,23.8,0.0,0.033,0.527778,5,1,0,0
102,2023,wiggian01,Andrew Wiggins,GOLDEN STATE WARRIORS,27,0.500000,32.162162,17.108108,2.297297,14.297297,...,0.564,7.9,21.5,0.4,0.087,0.500000,7,0,0,0
103,2023,willizi01,Zion Williamson,NEW ORLEANS PELICANS,22,0.402778,32.965517,26.000000,4.586207,16.172414,...,0.652,14.6,30.3,1.8,0.175,0.478873,12,0,0,0
104,2023,youngtr01,Trae Young,ATLANTA HAWKS,24,0.876712,34.875000,26.734375,10.031250,19.609375,...,0.573,14.9,33.1,3.2,0.128,0.492958,8,0,0,0

# Export final df

In [107]:
#df_final.to_csv("../Data/final_cleaned_data.csv")
#df_final_2023.to_csv("../Data/final_cleaned_data_2023.csv")