In [29]:
import requests

import pandas as pd

from bs4 import BeautifulSoup

In [30]:
season_list = []
for i in range(1950, 2023):
    first = str(i)
    second = str(int(first[2:])+1)
    if len(second) == 1:
        season = first + "-0" + second
    elif len(second) == 3:
        second = "2000"
        season = first + "-" + second
    else:
        season = first + "-" + second
    season_list.append(season)

In [31]:
season_list

['1950-51',
 '1951-52',
 '1952-53',
 '1953-54',
 '1954-55',
 '1955-56',
 '1956-57',
 '1957-58',
 '1958-59',
 '1959-60',
 '1960-61',
 '1961-62',
 '1962-63',
 '1963-64',
 '1964-65',
 '1965-66',
 '1966-67',
 '1967-68',
 '1968-69',
 '1969-70',
 '1970-71',
 '1971-72',
 '1972-73',
 '1973-74',
 '1974-75',
 '1975-76',
 '1976-77',
 '1977-78',
 '1978-79',
 '1979-80',
 '1980-81',
 '1981-82',
 '1982-83',
 '1983-84',
 '1984-85',
 '1985-86',
 '1986-87',
 '1987-88',
 '1988-89',
 '1989-90',
 '1990-91',
 '1991-92',
 '1992-93',
 '1993-94',
 '1994-95',
 '1995-96',
 '1996-97',
 '1997-98',
 '1998-99',
 '1999-2000',
 '2000-01',
 '2001-02',
 '2002-03',
 '2003-04',
 '2004-05',
 '2005-06',
 '2006-07',
 '2007-08',
 '2008-09',
 '2009-10',
 '2010-11',
 '2011-12',
 '2012-13',
 '2013-14',
 '2014-15',
 '2015-16',
 '2016-17',
 '2017-18',
 '2018-19',
 '2019-20',
 '2020-21',
 '2021-22',
 '2022-23']

In [32]:
base_url = "https://en.wikipedia.org/wiki/"
duration = []
for season in season_list:
        try: 
            response = requests.get(url)
            soup = BeautifulSoup(response.text, 'html.parser')
            date_duration = soup.find('th', text='Duration').parent
            duration_text = date_duration.find('td', class_='infobox-data')
            ul = duration_text.find('ul')
            li = ul.find('li')
            date_range = li.text
            duration.append(date_range)



        except:
            try:
                url = base_url + season + "_NBA_season"
                response = requests.get(url)
                soup = BeautifulSoup(response.text, 'html.parser')
                date_duration = soup.find('th', text='Duration').parent
                date = date_duration.find("ul").text.split("\n")[0]
                duration.append(date)
            
            except:
                try:
                    response = requests.get(url)
                    soup = BeautifulSoup(response.text, 'html.parser')
                    date_duration = soup.find('th', text='Duration').parent
                    duration_text = date_duration.find('td', class_='infobox-data').contents
                    duration.append(duration_text[0])
                except:
                    duration.append("error")


                      if duration_text.find('ul'):
            date_range = None
            for li in duration_text.find('ul').find_all('li'):
                if li.text.startswith(season):
                    date_range = li.text
                    break
            if not date_range:

In [122]:
base_url = "https://en.wikipedia.org/wiki/"
duration = []
for season in season_list:
    try:
        url = base_url + season + "_NBA_season"
        response = requests.get(url)
        soup = BeautifulSoup(response.text, 'html.parser')
        date_duration = soup.find('th', text='Duration').parent
        duration_text = date_duration.find('td', class_='infobox-data')
        date_range = duration_text.find('ul')
        if date_range == None:
            text = duration_text.contents[0]
            duration.append(text)
        else:
            date_range = date_range.find('li')
            date_content = date_range.contents
            if len(date_range) == 1:
                a = date_range.text
                duration.append(a)
            else:
                date_content = li.contents[0]
                date_content = date_range.contents
                if len(date_range) == 1:
                    duration.append(date_range.text)
                else:
                    date_content = li.contents[0]
                    duration.append(date_content)
    except:
        duration.append("error")

In [123]:
duration_df = pd.DataFrame({"season": season_list, "duration": duration})

In [128]:
duration_df

     season                           duration
0   1950-51  October 31, 1950 – March 18, 1951
1   1951-52  November 1, 1951 – March 16, 1952
2   1952-53  October 31, 1952 – March 17, 1953
3   1953-54  October 30, 1953 – March 14, 1954
4   1954-55  October 30, 1954 – March 14, 1955
..      ...                                ...
68  2018-19  October 16, 2018 – April 10, 2019
69  2019-20  October 22, 2019 – March 11, 2020
70  2020-21   December 22, 2020 – May 16, 2021
71  2021-22  October 19, 2021 – April 10, 2022
72  2022-23   October 18, 2022 – April 9, 2023

[73 rows x 2 columns]

In [132]:
duration_df.to_csv('/Users/annabelitong/desktop/annabel/uni/ds105l/group_project/DS105L-Project/Data/season_duration.csv', index=False)