In [6]:
import pandas as pd

In [7]:
df_all_bbc = []

for i in range(10, 24): 
    df_partial = pd.read_csv(f"../../Data/news_final_data/bbc_20{i}_unique.csv") 
    df_all_bbc.append(df_partial) 

len(df_all_bbc)

14

In [8]:
df_all_nba = [] 

for i in range(16, 21): 
    df_partial = pd.read_csv(f"../../Data/news_final_data/nba_20{i}_unique.csv") 
    df_all_nba.append(df_partial) 

len(df_all_nba)

5

In [9]:
df_bbc = pd.concat(df_all_bbc)
df_bbc.drop("url", axis = 1, inplace = True) 
df_bbc.rename(columns={
    "time": "season", 
    "most_frequent_name": "name"
}, inplace = True)
df_bbc

,season,name,textblob_sentiment,sentiment_bert_average_score,sentiment_xlnet_average_score,bert_relevance,relevance_score,frequency
0,2010,Al Harrington,0.032282,0.615266,0.610274,0.527045,0.000641,3
1,2010,Al Horford,0.048422,0.597507,0.548171,0.528132,0.000962,2
2,2010,Al Jefferson,0.073152,0.588793,0.585076,0.527361,0.002477,3
3,2010,Allen Iverson,0.000000,0.529667,0.550255,0.524040,0.000000,1
4,2010,Amar'e Stoudemire,0.000000,0.528092,0.706781,0.543719,0.000000,1
...,...,...,...,...,...,...,...,...
91,2023,Tyrese Haliburton,0.089087,0.552813,0.547047,0.590057,0.017504,1
92,2023,Tyrese Maxey,0.161708,0.563601,0.537964,0.600695,0.010654,1
93,2023,Wendell Carter Jr.,0.103490,0.562028,0.558659,0.605680,0.016315,1
94,2023,Zach LaVine,0.149753,0.574620,0.568527,0.588150,0.007415,6
95,2023,Zion Williamson,0.111393,0.555198,0.565584,0.583325,0.011758,6

In [10]:
df_nba = pd.concat(df_all_nba)
df_nba.drop(["Unnamed: 0", "url"], axis = 1, inplace = True) 
df_nba.rename(columns={
    "time": "season", 
    "most_frequent_name": "name" 
}, inplace = True)
df_nba[df_nba["frequency"] >= 20]

,season,name,textblob_Sentiment,nltk_Sentiment,relevance_score,bert_relevance,credit_article,credit_followers,credit_tweets,frequency
2,2016,Andrew Wiggins,0.086508,0.086508,0.054786,0.623969,12237.564103,46808.846154,52904.384615,39
3,2016,Anthony Davis,0.075360,0.075360,0.105925,0.624723,8566.531915,39816.106383,56508.978723,47
8,2016,Brook Lopez,0.085875,0.085875,0.061888,0.614346,19194.033333,74243.200000,82916.400000,30
10,2016,Carmelo Anthony,0.097486,0.097486,0.068769,0.621795,6366.804348,26928.739130,29641.304348,46
12,2016,Chris Paul,0.074875,0.074875,0.067820,0.620527,19730.153846,76366.523077,85144.907692,65
...,...,...,...,...,...,...,...,...,...,...
66,2020,Spencer Dinwiddie,0.077606,0.077606,0.104272,0.567157,16788.304348,38861.043478,41607.956522,23
67,2020,T.J. Warren,0.075217,0.075217,0.111589,0.602439,11218.357143,39736.750000,44394.750000,28
69,2020,Tobias Harris,0.094988,0.094988,0.080843,0.546131,30346.280000,51458.360000,63772.520000,25
70,2020,Trae Young,0.080657,0.080657,0.149031,0.549218,13151.638889,41648.916667,48645.430556,72
73,2020,Zach LaVine,0.066251,0.066251,0.087470,0.563624,16874.205882,50327.764706,60064.176471,34

In [11]:
df_bbc_2023 = df_bbc[df_bbc["season"] == 2023]
df_bbc = df_bbc[df_bbc["season"] != 2023]

In [12]:
#df_bbc_2023.to_csv("../../Data/semi_processed_data/bbc_data_2023.csv")
#df_bbc.to_csv("../../Data/semi_processed_data/bbc_data.csv")